services:
  _defaults:
    public: false
    autowire: true

  OpenCFP\Infrastructure\Auth\:
    resource: '%kernel.project_dir%/src/Infrastructure/Auth/*'

  OpenCFP\Infrastructure\CacheWarmer\:
    resource: '%kernel.project_dir%/src/Infrastructure/CacheWarmer/*'
    tags: [kernel.cache_warmer]

  OpenCFP\Infrastructure\Crypto\PseudoRandomStringGenerator: ~

  OpenCFP\Infrastructure\Event\:
    resource: '%kernel.project_dir%/src/Infrastructure/Event/*'
    tags: [kernel.event_subscriber]
    bind:
      OpenCFP\Domain\Services\RequestValidator: '@OpenCFP\Infrastructure\Auth\CsrfValidator'

  OpenCFP\Infrastructure\Repository\IlluminateUserRepository: ~

  OpenCFP\Infrastructure\Validation\RequestValidator: ~

  Illuminate\Validation\Factory: ~

  Illuminate\Filesystem\Filesystem: ~

  Illuminate\Contracts\Container\Container:
    class: Illuminate\Container\Container

  Illuminate\Contracts\Translation\Translator:
    class: Illuminate\Translation\Translator
    autowire: false
    arguments:
      - '@translation_loader'
      - 'en'

  translation_loader:
    class: Illuminate\Translation\FileLoader
    arguments:
      $path: '%kernel.project_dir%/resources/lang'
