<?php

use Phinx\Migration\AbstractMigration;

class Airports extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        $this->execute("
            CREATE TABLE `airports` (
              `code` char(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
              `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
              `country` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
              PRIMARY KEY (`code`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
        ");

        $this->execute("
            INSERT INTO `airports` (`name`, `country`, `code`)
            VALUES
            ('Al Arish','Egypt','AAC'),
            ('Annaba','Algeria','AAE'),
            ('Alborg','Denmark','AAL'),
            ('Al Ain','United Arab Emirates','AAN'),
            ('Aarhus','Denmark','AAR'),
            ('Altay','PR China','AAT'),
            ('Abadan','Iran','ABD'),
            ('Allentown (PA)','USA','ABE'),
            ('Abilene (TX)','USA','ABI'),
            ('Abidjan','Cote d\'Ivoire','ABJ'),
            ('Bamaga','Australia','ABM'),
            ('Albuquerque (NM)','USA','ABQ'),
            ('Aberdeen (SD)','USA','ABR'),
            ('Abu Simbel','Egypt','ABS'),
            ('Abuja - Nnamdi Azikiwe International Airport','Nigeria','ABV'),
            ('Albury','Australia','ABX'),
            ('Albany (GA)','USA','ABY'),
            ('Aberdeen','United Kingdom','ABZ'),
            ('Acapulco','Mexico','ACA'),
            ('Accra - Kotoka International Airport','Ghana','ACC'),
            ('Arrecife/Lanzarote','Spain','ACE'),
            ('Altenrhein','Switzerland','ACH'),
            ('Alderney','Channel Islands','ACI'),
            ('Nantucket (MA)','USA','ACK'),
            ('Waco (TX)','USA','ACT'),
            ('Eureka (CA)','USA','ACV'),
            ('Atlantic City (NJ) - Atlantic City International','USA','ACY'),
            ('Adana','Turkey','ADA'),
            ('Izmir - Adnan Menderes','Turkey','ADB'),
            ('Addis Ababa - Bole International Airport','Ethiopia','ADD'),
            ('Aden - Aden International Airport','Yemen','ADE'),
            ('Adiyaman','Turkey','ADF'),
            ('Amman - Amman-Marka International Airport','Jordan','ADJ'),
            ('Adelaide','Australia','ADL'),
            ('Kodiak (AK)','USA','ADQ'),
            ('Alldays','South Africa','ADY'),
            ('San Andres','Colombia','ADZ'),
            ('Abeche','Chad','AEH'),
            ('Buenos Aires Jorge Newbery','Argentina','AEP'),
            ('Adler/Sochi','Russia','AER'),
            ('Alesund','Norway','AES'),
            ('Agadir','Morocco','AGA'),
            ('Augsburg - Augsbur gAirport','Germany','AGB'),
            ('Malaga','Spain','AGP'),
            ('Augusta (GA)','USA','AGS'),
            ('Aguascaliente','Mexico','AGU'),
            ('Aggeneys','South Africa','AGZ'),
            ('Khamis Mushayat','Saudi Arabia','AHB'),
            ('Athens (GA)','USA','AHN'),
            ('Alghero Sassari','Italy','AHO'),
            ('Al Hoceima','Morocco','AHU'),
            ('Ajaccio','France','AJA'),
            ('Jouf','Saudi Arabia','AJF'),
            ('Anjouan - Anjouan Airport','Comoros (Comores)','AJN'),
            ('Aracaju','Brazil','AJU'),
            ('Agades','Niger','AJY'),
            ('Auckland - Auckland International Airport','New Zealand','AKL'),
            ('King Salomon (AK)','USA','AKN'),
            ('Akrotiri - RAF','Cyprus','AKT'),
            ('Almaty (Alma Ata) - Almaty International Airport','Kazakhstan','ALA'),
            ('Albany (NY) - Albany International Airport','USA','ALB'),
            ('Alicante','Spain','ALC'),
            ('Alta','Norway','ALF'),
            ('Algiers Houari Boumediene Airport','Algeria','ALG'),
            ('Albany','Australia','ALH'),
            ('Alexander Bay - Kortdoorn','South Africa','ALJ'),
            ('Waterloo IA','USA','ALO'),
            ('Aleppo','Syria','ALP'),
            ('Andorra La Vella - Heliport','Andorra','ALV'),
            ('Walla Walla (WA)','USA','ALW'),
            ('Alexandria - El Nhouza Airport','Egypt','ALY'),
            ('Amarillo (TX)','USA','AMA'),
            ('Ahmedabad','India','AMD'),
            ('Amman - Queen Alia International Airport','Jordan','AMM'),
            ('Amsterdam - Amsterdam Airport Schiphol','Netherlands','AMS'),
            ('Anniston (AL)','USA','ANB'),
            ('Anchorage (AK) - Ted Stevens Anchorage International','USA','ANC'),
            ('Ankara','Turkey','ANK'),
            ('Antwerp','Belgium','ANR'),
            ('Antigua V.C. Bird International','Antigua and Barbuda','ANU'),
            ('Ancona - Ancona Falconara Airport','Italy','AOI'),
            ('Aomori','Japan','AOJ'),
            ('Karpathos','Greece','AOK'),
            ('Altoona (PA)','USA','AOO'),
            ('Naples (FL)','USA','APF'),
            ('Apia - Faleolo International Airport','Samoa','APW'),
            ('Aqaba','Jordan','AQJ'),
            ('Ann Arbor (MI)','USA','ARB'),
            ('Arkhangelsk','Russia','ARH'),
            ('Arusha','Tanzania','ARK'),
            ('Stockholm - Arlanda','Sweden','ARN'),
            ('Ashgabat - Saparmurat Turkmenbashy Int. Airport','Turkmenistan','ASB'),
            ('Aspen (CO) - Aspen-Pitkin County Airport','USA','ASE'),
            ('Amami','Japan','ASJ'),
            ('Yamoussoukro','Côte d\'Ivoire','ASK'),
            ('Asmara - Asmara International','Eritrea','ASM'),
            ('Alice Springs','Australia','ASP'),
            ('Kayseri','Turkey','ASR'),
            ('Asuncion - Asunción International Airport','Paraguay','ASU'),
            ('Aswan - Daraw Airport','Egypt','ASW'),
            ('Athens - Elefthérios Venizélos International Airport','Greece','ATH'),
            ('Atlanta (GA) - Hartsfield Atlanta International Airport','USA','ATL'),
            ('Athens (OH)','USA','ATO'),
            ('Amritsar','India','ATQ'),
            ('Appelton/Neenah/Menasha (WI)','USA','ATW'),
            ('Watertown (SD)','USA','ATY'),
            ('Assiut','Egypt','ATZ'),
            ('Aruba - Reina Beatrix International Oranjestad','Aruba','AUA'),
            ('Abu Rudeis','Egypt','AUE'),
            ('Augusta (ME) - Augusta State Airport','USA','AUG'),
            ('Abu Dhabi - Abu Dhabi International','United Arab Emirates','AUH'),
            ('Aurillac','France','AUR'),
            ('Austin (TX) - Austin-Bergstrom Airport','USA','AUS'),
            ('Asheville (NC)','USA','AVL'),
            ('Wilkes Barre/Scranton (PA)','USA','AVP'),
            ('Anguilla','Anguilla','AXA'),
            ('Altus','USA','AXS'),
            ('Akita','Japan','AXT'),
            ('Ayers Rock - Connellan','Australia','AYQ'),
            ('Ayr','Australia','AYR'),
            ('Antalya','Turkey','AYT'),
            ('Aiyura','Papua New Guinea','AYU'),
            ('Ayawasi','Indonesia','AYW'),
            ('Amazon Bay','Papua New Guinea','AZB'),
            ('Kalamazoo/Battle Creek (MI)','USA','AZO'),
            ('Mexico City - Atizapan','Mexico','AZP'),
            ('Samana - Samaná El Catey International Airport','Dominican Republic','AZS'),
            ('Bahrain - Bahrain International Airport','Bahrain','BAH'),
            ('Baku - Heydar Aliyev International Airport','Azerbaijan','BAK'),
            ('Barranquilla','Colombia','BAQ'),
            ('Bhubaneswar','India','BBI'),
            ('Berberati','Central African Republic','BBT'),
            ('Bambari','Central African Republic','BBY'),
            ('Barcelona','Spain','BCN'),
            ('Jinka - Baco/Jinka Airport','Ethiopia','BCO'),
            ('Bermuda - L.F. Wade International Airport','Bermuda','BDA'),
            ('Bundaberg','Australia','BDB'),
            ('Hartford (CT) /Springfield (MA)','USA','BDL'),
            ('Bandung - Husein Sastranegara International Airport','Indonesia','BDO'),
            ('Baroda','India','BDQ'),
            ('Bridgeport (CT)','USA','BDR'),
            ('Brindisi','Italy','BDS'),
            ('Bardufoss','Norway','BDU'),
            ('Benbecula','United Kingdom','BEB'),
            ('Belgrad (Beograd) - Belgrade Nikola Tesla International','Serbia','BEG'),
            ('Benton Harbour (MI)','USA','BEH'),
            ('Belem - Val de Cans International Airport','Brazil','BEL'),
            ('Benghazi (Bengasi)','Libya','BEN'),
            ('Newcastle - Belmont','Australia','BEO'),
            ('Berlin','Germany','BER'),
            ('Brest','France','BES'),
            ('Bethel (AK)','USA','BET'),
            ('Beira','Mozambique','BEW'),
            ('Beirut - Beirut Rafic Hariri International Airport','Lebanon','BEY'),
            ('Bradford/Warren (PA) /Olean (NY)','USA','BFD'),
            ('Bakersfield (CA)','USA','BFL'),
            ('Bloemfontein - Bloemfontein Airport','South Africa','BFN'),
            ('Buffalo Range','Zimbabwe','BFO'),
            ('Belfast - Belfast International Airport','United Kingdom','BFS'),
            ('Bucaramanga','Colombia','BGA'),
            ('Bangui - M\'Poko International Airport','Central African Republic','BGF'),
            ('Bridgetown - Grantley Adams International','Barbados','BGI'),
            ('Johnson City (NY) - Binghamton/Endicott/Johnson','USA','BGM'),
            ('Bergen','Norway','BGO'),
            ('Bangor (ME)','USA','BGR'),
            ('Bangassou','Central African Republic','BGU'),
            ('Bagdad - Baghdad International Airport','Iraq','BGW'),
            ('Bergamo/Milan - Orio Al Serio','Italy','BGY'),
            ('Bullhead City (NV)','USA','BHC'),
            ('Belfast - George Best Belfast City Airport','United Kingdom','BHD'),
            ('Blenheim','New Zealand','BHE'),
            ('Birmingham (AL)','USA','BHM'),
            ('Bhopal','India','BHO'),
            ('Broken Hill','Australia','BHQ'),
            ('Bahawalpur','Pakistan','BHV'),
            ('Birmingham - Birmingham International Airport','United Kingdom','BHX'),
            ('Bastia','France','BIA'),
            ('Billings (MT)','USA','BIL'),
            ('Bilbao','Spain','BIO'),
            ('Biarritz','France','BIQ'),
            ('Bismarck (ND) - Bismarck Municipal Airport','USA','BIS'),
            ('Bria','Central African Republic','BIV'),
            ('Bemidji (MN)','USA','BJI'),
            ('Banjul - Banjul International Airport (Yundum International)','Gambia','BJL'),
            ('Bujumbura - Bujumbura International Airport','Burundi','BJM'),
            ('Bodrum - Milas Airport','Turkey','BJV'),
            ('Leon','Mexico','BJX'),
            ('Badajoz','Spain','BJZ'),
            ('Kota Kinabalu','Malaysia','BKI'),
            ('Bangkok Suvarnabhumi International','Thailand','BKK'),
            ('Cleveland (OH)  Burke Lakefront','USA','BKL'),
            ('Bamako - Bamako-Sénou International Airport','Mali','BKO'),
            ('Beckley (WV)','USA','BKW'),
            ('Brookings (SD)','USA','BKX'),
            ('Barcelona','Venezuela','BLA'),
            ('Bluefield (WV)','USA','BLF'),
            ('Bellingham (WA)','USA','BLI'),
            ('Blackpool','United Kingdom','BLK'),
            ('Billund','Denmark','BLL'),
            ('Bologna','Italy','BLQ'),
            ('Bangalore','India','BLR'),
            ('Blackwater','Australia','BLT'),
            ('Blantyre (Mandala) - Chileka International Airport','Malawi','BLZ'),
            ('Stockholm - Bromma','Sweden','BMA'),
            ('Broome','Australia','BME'),
            ('Bloomington (IN)','USA','BMG'),
            ('Bloomington (IL)','USA','BMI'),
            ('Brampton Island','Australia','BMP'),
            ('Nashville (TN)','USA','BNA'),
            ('Brisbane','Australia','BNE'),
            ('Ballina','Australia','BNK'),
            ('Broennoeysund','Norway','BNN'),
            ('Bannu','Pakistan','BNP'),
            ('Bora Bora','French Polynesia','BOB'),
            ('Bordeaux - Bordeaux Airport','France','BOD'),
            ('Bogota - El Nuevo Dorado International Airport','Colombia','BOG'),
            ('Bournemouth','United Kingdom','BOH'),
            ('Boise (ID) - Boise Air Terminal','USA','BOI'),
            ('Bourgas/Burgas','Bulgaria','BOJ'),
            ('Bombay (Mumbai) - Chhatrapati Shivaji International','India','BOM'),
            ('Bonaire','Netherlands Antilles','BON'),
            ('Bodo','Norway','BOO'),
            ('Boston (MA) - General Edward Lawrence Logan','USA','BOS'),
            ('Bobo/Dioulasso','Burkina Faso','BOY'),
            ('Beaumont/Pt. Arthur (TX)','USA','BPT'),
            ('Brunswick (GA)','USA','BQK'),
            ('Aguadilla','Puerto Rico','BQN'),
            ('San Carlos de Bariloche','Argentina','BRC'),
            ('Brainerd (MN)','USA','BRD'),
            ('Bremen - Bremen Airport (Flughafen Bremen)','Germany','BRE'),
            ('Bari','Italy','BRI'),
            ('Burlington IA','USA','BRL'),
            ('Berne Bern-Belp','Switzerland','BRN'),
            ('Barra (the famous tidal beach landing)','United Kingdom','BRR'),
            ('Bristol','United Kingdom','BRS'),
            ('Brussels - Brussels Airport','Belgium','BRU'),
            ('Brasilia - President Juscelino Kubitschek International','Brazil','BSB'),
            ('Basel','Switzerland','BSL'),
            ('Basra Basrah','Iraq','BSR'),
            ('Butte (MT)','USA','BTM'),
            ('Baton Rouge (LA) - Baton Rouge Metropolitan Airport','USA','BTR'),
            ('Bratislava - M. R. Štefánik Airport','Slovakia','BTS'),
            ('Bintulu','Malaysia','BTU'),
            ('Burlington (VT)','USA','BTV'),
            ('Budapest - Budapest Ferihegy International Airport','Hungary','BUD'),
            ('Buenos Aires','Argentina','BUE'),
            ('Buffalo/Niagara Falls (NY)','USA','BUF'),
            ('Benguela','Angola','BUG'),
            ('Bucharest','Romania','BUH'),
            ('Bulawayo','Zimbabwe','BUQ'),
            ('Burbank (CA)','USA','BUR'),
            ('Boa Vista','Brazil','BVB'),
            ('Baltimore (MD) - Washington International Airport','USA','BWI'),
            ('Bandar Seri Begawan - Brunei International Airport','Brunei','BWN'),
            ('Burnie (Wynyard)','Australia','BWT'),
            ('Bissau - Osvaldo Vieiro International Airport','Guinea-Bissau','BXO'),
            ('Borrego Springs (CA)','USA','BXS'),
            ('Bouake','Cote d\'Ivoire','BYK'),
            ('Bayreuth - Bindlacher-Berg','Germany','BYU'),
            ('Belize City - Philip S.W.Goldson International','Belize','BZE'),
            ('Barisal','Bangladesh','BZL'),
            ('Bozeman (MT)','USA','BZN'),
            ('Brazzaville - Maya-Maya Airport','Congo (ROC)','BZV'),
            ('Cabinda','Angola','CAB'),
            ('Columbia (SC) - Columbia Metropolitan Airport','USA','CAE'),
            ('Cagliari','Italy','CAG'),
            ('Cairo - Cairo International Airport','Egypt','CAI'),
            ('Akron (OH)','USA','CAK'),
            ('Campbeltown','United Kingdom','CAL'),
            ('Guangzhou (Canton) - Baiyun International Airport','Guangdong PR China','CAN'),
            ('Casablanca','Morocco','CAS'),
            ('Cayenne - Cayenne-Rochambeau Airport','French Guiana','CAY'),
            ('Cochabamba','Bolivia','CBB'),
            ('Cambrigde','United Kingdom','CBG'),
            ('Canberra - Canberra Airport','Australia','CBR'),
            ('Cottbus - Cottbus-Drewitz Airport','Germany','CBU'),
            ('Calicut','India','CCJ'),
            ('Concord (CA) - Buchanan Field','USA','CCR'),
            ('Caracas - Simón Bolívar International Airport','Venezuela','CCS'),
            ('Calcutta (Kolkata) - Netaji Subhas Chandra','India','CCU'),
            ('Chub Cay','Bahamas','CCZ'),
            ('Cedar City (UT)','USA','CDC'),
            ('Paris - Charles de Gaulle','France','CDG'),
            ('Cordova (AK)','USA','CDV'),
            ('Crescent City (CA)','USA','CEC'),
            ('Ceduna','Australia','CED'),
            ('Ciudad Obregon','Mexico','CEN'),
            ('Cessnock','Australia','CES'),
            ('Clermont Ferrand','France','CFE'),
            ('Cienfuegos - Jaime González Airport','Cuba','CFG'),
            ('Donegal (Carrickfin)','Ireland','CFN'),
            ('Coffs Harbour','Australia','CFS'),
            ('Corfu','Greece','CFU'),
            ('Craig (AK)','USA','CGA'),
            ('Cuiaba - Marechal Rondon International Airport','Brazil','CGB'),
            ('Sao Paulo - Congonhas','Brazil','CGH'),
            ('Jakarta - Soekarno-Hatta International','Indonesia','CGK'),
            ('Cologne - Cologne Airport (Flughafen Köln/Bonn)','Germany','CGN'),
            ('Chittagong','Bangladesh','CGP'),
            ('Changchun','Jilin PR China','CGQ'),
            ('Campo Grande','Brazil','CGR'),
            ('Ciudad Guayana','Venezuela','CGU'),
            ('Chattanooga (TN)','USA','CHA'),
            ('Christchurch','New Zealand','CHC'),
            ('Chaoyang Beijing - Chaoyang Airport','PR China','CHG'),
            ('Chicago (IL)','USA','CHI'),
            ('Charlottesville (VA)','USA','CHO'),
            ('Chania','Greece','CHQ'),
            ('Charleston (SC)','USA','CHS'),
            ('Rome - Ciampino','Italy','CIA'),
            ('Chico (CA)','USA','CIC'),
            ('Cedar Rapids IA','USA','CID'),
            ('Chipata','Zambia','CIP'),
            ('Canouan (island) - Canouan Airport','Saint Vincent & the Grenadines','CIW'),
            ('Coimbatore','India','CJB'),
            ('Calama - El Loa','Chile','CJC'),
            ('Chitral','Pakistan','CJL'),
            ('Ciudad Juarez','Mexico','CJS'),
            ('Clarksburg (WV)','USA','CKB'),
            ('Chongqing - Jiangbei International Airport','Sichuan PR China','CKG'),
            ('Conakry - Conakry International Airport','Guinea','CKY'),
            ('Carlsbad (CA)','USA','CLD'),
            ('Cleveland (OH)  Hopkins','USA','CLE'),
            ('College Station/Bryan (TX)','USA','CLL'),
            ('Port Angeles (WA)','USA','CLM'),
            ('Cali','Colombia','CLO'),
            ('Colima','Mexico','CLQ'),
            ('Charlotte (NC)','USA','CLT'),
            ('Calvi','France','CLY'),
            ('Colombo - Bandaranaike International Airport','Sri Lanka','CMB'),
            ('Ciudad Del Carmen','Mexico','CME'),
            ('Chambery','France','CMF'),
            ('Columbus (OH) - Port Columbus International Airport','USA','CMH'),
            ('Champaign (IL)','USA','CMI'),
            ('Casablanca Mohamed V','Morocco','CMN'),
            ('Clermont','Australia','CMQ'),
            ('Hancock (MI)','USA','CMX'),
            ('Constanta (Constanța) - Constanta Int\'l Airport','Romania','CND'),
            ('Belo Horizonte - Tancredo Neves International Airport','Brazil','CNF'),
            ('Cairns','Australia','CNS'),
            ('Chiang Mai - Chiang Mai International Airport','Thailand','CNX'),
            ('Cody/Powell/Yellowstone (WY)','USA','COD'),
            ('Cochin','India','COK'),
            ('Concord (NH) - Concord Municipal Airport','USA','CON'),
            ('Cotonou - Cotonou Cadjehoun Airport','Benin','COO'),
            ('Cordoba','Argentina','COR'),
            ('Colorado Springs (CO)','USA','COS'),
            ('Coober Pedy','Australia','CPD'),
            ('Copenhagen - Copenhagen Airport','Denmark','CPH'),
            ('Casper (WY)','USA','CPR'),
            ('Cape Town - Cape Town International Airport','South Africa','CPT'),
            ('Myrtle Beach (SC) - Grand Strand Airport','USA','CRE'),
            ('Carnot','Central African Republic','CRF'),
            ('Jacksonville (FL) - Craig Municipal   ','USA','CRG'),
            ('Corpus Christi (TX)','USA','CRP'),
            ('Charleston (WV) - Yeager Airport','USA','CRW'),
            ('Columbus (GA)','USA','CSG'),
            ('Casino','Australia','CSI'),
            ('Carson City (NV)','USA','CSN'),
            ('Castaway','Fiji','CST'),
            ('Catania','Italy','CTA'),
            ('Cartagena - Rafael Núñez International Airport','Colombia','CTG'),
            ('Cooktown','Australia','CTN'),
            ('Sapporo - New Chitose Airport','Japan','CTS'),
            ('Chengdu - Shuangliu','Sichuan PR China','CTU'),
            ('Culiacan','Mexico','CUL'),
            ('Cancun','Mexico','CUN'),
            ('Curacao - Curaçao International Airport','Netherlands Antilles','CUR'),
            ('Chihuahua Gen Fierro Villalobos','Mexico','CUU'),
            ('Cincinnati (OH) - Cincinnati/Northern Kentucky Int\'l','USA','CVG'),
            ('Ciudad Victoria','Mexico','CVM'),
            ('Carnarvon','Australia','CVQ'),
            ('Coventry - Baginton','United Kingdom','CVT'),
            ('Wausau/Stevens Point (WI)','USA','CWA'),
            ('Curitiba - Afonso Pena International Airport','Brazil','CWB'),
            ('Cardiff - Cardiff Airport','United Kingdom','CWL'),
            ('Kiritimati (island) - Cassidy International Airport','Kiribati','CXI'),
            ('Charters Towers','Australia','CXT'),
            ('Cheyenne (WY) - Cheyenne Regional Airport','USA','CYS'),
            ('Cuyo','Philippines','CYU'),
            ('Chichen Itza','Mexico','CZA'),
            ('Constantine','Algeria','CZL'),
            ('Cozmel','Mexico','CZM'),
            ('Daytona Beach (FL)','USA','DAB'),
            ('Dhaka - Zia International Airport','Bangladesh','DAC'),
            ('Dallas (TX)  Love Field','USA','DAL'),
            ('Damascus International','Syria','DAM'),
            ('Danville (VA)','USA','DAN'),
            ('Dar es Salam (Daressalam) - Julius Nyerere Int\'l','Tanzania','DAR'),
            ('Dayton (OH)','USA','DAY'),
            ('Dubbo','Australia','DBO'),
            ('Dubuque IA','USA','DBQ'),
            ('Dubrovnik','Croatia (Hrvatska)','DBV'),
            ('Dalby','Australia','DBY'),
            ('Washington DC - Ronald Reagan National','USA','DCA'),
            ('Daydream Island','Australia','DDI'),
            ('Decatur (IL)','USA','DEC'),
            ('Delhi - Indira Gandhi International Airport','India','DEL'),
            ('Denver (CO) - Denver International Airport','USA','DEN'),
            ('Detroit (MI)  Coleman A. Young Municipal','USA','DET'),
            ('Fort Worth (TX) - Dallas/Fort Worth International Airport','USA','DFW'),
            ('Dhahran','Saudi Arabia','DHA'),
            ('Dothan (AL)','USA','DHN'),
            ('Dili - Nicolau Lobato International Airport','Timor Leste (East Timor)','DIL'),
            ('Jambi - Sultan Taha Syarifudn','Indonesia ','DJB'),
            ('Djerba','Tunisia','DJE'),
            ('Jayapura - Sentani','Indonesia','DJJ'),
            ('Daloa','Cote d\'Ivoire','DJO'),
            ('Dunk Island','Australia','DKI'),
            ('Dakar - Léopold Sédar Senghor International Airport','Senegal','DKR'),
            ('Douala','Cameroon','DLA'),
            ('Dalian - Zhoushuizi International Airport','Liaoning PR China','DLC'),
            ('Dillingham (AK)','USA','DLG'),
            ('Duluth (MN) /Superior (WI)','USA','DLH'),
            ('Dalaman','Turkey','DLM'),
            ('Disneyland Paris','France','DLP'),
            ('Moscow - Domodedovo','Russia','DME'),
            ('Bangkok Don Muang','Thailand','DMK'),
            ('Dammam King Fahad International','Saudi Arabien','DMM'),
            ('Dundee','United Kingdom','DND'),
            ('Dinard','France','DNR'),
            ('Denizli','Turkey','DNZ'),
            ('Dodoma - Dodoma Airport','Tanzania','DOD'),
            ('Doha - Doha International Airport','Qatar','DOH'),
            ('Melville Hall','Dominica','DOM'),
            ('Devonport','Australia','DPO'),
            ('Denpasar/Bali','Indonesia','DPS'),
            ('Derby','Australia','DRB'),
            ('Durango (CO)','USA','DRO'),
            ('Dresden - Dresden Airport','Germany','DRS'),
            ('Darwin','Australia','DRW'),
            ('Doncaster/Sheffield Robin Hood International Airport','United Kingdom','DSA'),
            ('Dera Ismail Khan - Dera Ismail Khan Airport','Pakistan','DSK'),
            ('Des Moines (IA) - Des Moines International Airport','USA','DSM'),
            ('Dortmund','Germany','DTM'),
            ('Detroit (MI)  Metropolitan Area','USA','DTT'),
            ('Detroit (MI)  Wayne County Airport','USA','DTW'),
            ('Dublin - Dublin International Airport','Ireland','DUB'),
            ('Dunedin','New Zealand','DUD'),
            ('Dubois (PA)','USA','DUJ'),
            ('Durban','South Africa','DUR'),
            ('Duesseldorf - Düsseldorf International Airport','Germany','DUS'),
            ('Dutch Harbor (AK)','USA','DUT'),
            ('Devils Lake (ND)','USA','DVL'),
            ('Dubai - Dubai International Airport','United Arab Emirates','DXB'),
            ('Dysart','Australia','DYA'),
            ('Dushanbe (Duschanbe) - Dushanbe Airport','Tajikistan','DYU'),
            ('Dzaoudzi','Mayotte','DZA'),
            ('Basel/Mulhouse','Switzerland/France','EAP'),
            ('San Sebastian','Spain','EAS'),
            ('Wenatchee (WA)','USA','EAT'),
            ('Eau Clarie (WI)','USA','EAU'),
            ('Elba Island Marina Di Campo','Italy','EBA'),
            ('Entebbe - Entebbe International Airport','Uganda','EBB'),
            ('Esbjerg','Denmark','EBJ'),
            ('St. Etienne','France','EBU'),
            ('Edinburgh - Edinburgh Airport','Scotland UK','EDI'),
            ('Emerald','Australia','EDR'),
            ('Bergerac - Roumanieres','France','EGC'),
            ('Vail (CO)','USA','EGE'),
            ('Egilsstadir','Iceland','EGS'),
            ('Eindhoven','Netherlands','EIN'),
            ('Beef Island - Terrance B. Lettsome','Virgin Islands (British)','EIS'),
            ('Elkhart (IN)','USA','EKI'),
            ('Elko (NV)','USA','EKO'),
            ('North Eleuthera','Bahamas','ELH'),
            ('Ellisras','South Africa','ELL'),
            ('Elmira (NY)','USA','ELM'),
            ('El Paso (TX) - El Paso International Airport','USA','ELP'),
            ('East London','South Africa','ELS'),
            ('Ely (NV)','USA','ELY'),
            ('Nottingham - East Midlands','United Kingdom','EMA'),
            ('Emerald','Australia','EMD'),
            ('El Minya','Egypt','EMY'),
            ('Kenai (AK)','USA','ENA'),
            ('Nancy','France','ENC'),
            ('Enontekioe','Finland','ENF'),
            ('Esperance','Australia','EPR'),
            ('Erzincan','Turkey','ERC'),
            ('Erfurt - Erfurt Airport (Flughafen Erfurt)','Germany','ERF'),
            ('Erie (PA)','USA','ERI'),
            ('Windhoek - Eros','Namibia','ERS'),
            ('Erzurum','Turkey','ERZ'),
            ('Ankara - Esenboğa International Airport','Turkey','ESB'),
            ('Escanaba (MI)','USA','ESC'),
            ('Alexandria - Esler Field','USA (LA)','ESF'),
            ('Elat','Israel','ETH'),
            ('Metz/Nancy Metz-Nancy-Lorraine','France','ETZ'),
            ('Eugene (OR)','USA','EUG'),
            ('Evenes','Norway','EVE'),
            ('Eriwan (Yerevan Jerevan)','Armenia','EVN'),
            ('Evansville (IN)','USA','EVV'),
            ('New Bern (NC)','USA','EWN'),
            ('New York - Newark (NJ)','USA','EWR'),
            ('Exeter','United Kingdom','EXT'),
            ('Key West (FL)','USA','EYW'),
            ('Buenos Aires Ezeiza International Airport','Argentina','EZE'),
            ('Faroer - Vágar Airport','Denmark','FAE'),
            ('Fairbanks (AK)','USA','FAI'),
            ('Faro','Portugal','FAO'),
            ('Fargo (ND) (MN)','USA','FAR'),
            ('Fresno (CA)','USA','FAT'),
            ('Fayetteville/Ft. Bragg (NC)','USA','FAY'),
            ('Lumbumbashi','Congo (DRC)','FBM'),
            ('Oslo - Fornebu','Norway','FBU'),
            ('Kalispell (MT)','USA','FCA'),
            ('Rome - Fuimicino','Italy','FCO'),
            ('Fort de France - Martinique Aimé Césaire International','Martinique','FDF'),
            ('Friedrichshafen - Bodensee-Airport Friedrichshafen','Germany','FDH'),
            ('Fes','Morocco','FEZ'),
            ('Fort Huachuca/Sierra Vista (AZ)','USA','FHU'),
            ('Fair Isle (Shetland)','United Kingdom','FIE'),
            ('Kinshasa - N\'Djili','Congo (DRC)','FIH'),
            ('Fujairah International Airport','United Arab Emirates','FJR'),
            ('Karlsruhe-Baden - Soellingen','Germany','FKB'),
            ('Kisangani','Congo (DRC)','FKI'),
            ('Franklin/Oil City (PA)','USA','FKL'),
            ('Fukushima - Fukushima Airport','Japan','FKS'),
            ('Flagstaff (AZ)','USA','FLG'),
            ('Fort Lauderdale/Hollywood (FL)','USA','FLL'),
            ('Florianopolis','Brazil','FLN'),
            ('Florence (SC)','USA','FLO'),
            ('Florence (Firenze) - Peretola Airport','Italy','FLR'),
            ('Farmington (NM)','USA','FMN'),
            ('Muenster/Osnabrueck','Germany','FMO'),
            ('Fort Myers Metropolitan Area (FL)','USA','FMY'),
            ('Freetown - Freetown-Lungi International Airport','Sierra Leone','FNA'),
            ('Funchal','Portugal','FNC'),
            ('Nimes','France','FNI'),
            ('Pyongyang - Sunan International Airport','North Korea','FNJ'),
            ('Flint (MI)','USA','FNT'),
            ('Fort Dodge IA','USA','FOD'),
            ('Fortaleza - Pinto Martins Airport','Brazil','FOR'),
            ('Foula (Shetland)','United Kingdom','FOU'),
            ('Freeport - Grand Bahama International Airport','Bahamas','FPO'),
            ('Frankfurt/Main - Frankfurt Airport (Rhein-Main-Flughafen)','Germany','FRA'),
            ('Fort Riley (KS) - Marshall AAF','USA','FRI'),
            ('Frejus','France','FRJ'),
            ('Floro','Norway','FRO'),
            ('Bishkek - Manas International Airport','Kyrgyzstan','FRU'),
            ('Francistown','Botswana','FRW'),
            ('Figari','France','FSC'),
            ('Sioux Falls (SD)','USA','FSD'),
            ('Fort Smith (AR)','USA','FSM'),
            ('St. Pierre NF','Canada','FSP'),
            ('Fuerteventura','Spain','FUE'),
            ('Fukuoka','Japan','FUK'),
            ('Futuna','Wallis and Futuna Islands','FUT'),
            ('Fort Wayne (IN)','USA','FWA'),
            ('Fayetteville (AR)','USA','FYV'),
            ('Gadsden (AL)','USA','GAD'),
            ('Yamagata Junmachi','Japan','GAJ'),
            ('Guwahati','India','GAU'),
            ('Gaborone - Sir Seretse Khama International Airport','Botswana','GBE'),
            ('Gilette (WY)','USA','GCC'),
            ('Guernsey','Channel Islands','GCI'),
            ('Grand Cayman - Owen Roberts International','Cayman Islands','GCM'),
            ('Grand Canyon (AZ)','USA','GCN'),
            ('Guadalajara','Mexico','GDL'),
            ('Gdansk','Poland','GDN'),
            ('Glendive (MT)','USA','GDV'),
            ('Spokane (WA)','USA','GEG'),
            ('Georgetown - Cheddi Jagan International Airport','Guyana','GEO'),
            ('Geraldton','Australia','GET'),
            ('Geelong','Australia','GEX'),
            ('Griffith','Australia','GFF'),
            ('Grand Forks (ND)','USA','GFK'),
            ('Longview/Kilgore (TX)','USA','GGG'),
            ('Glasgow (MT)','USA','GGW'),
            ('Govenors Harbour','Bahamas','GHB'),
            ('Gibraltar','Gibraltar','GIB'),
            ('Rio de Janeiro - Galeao','Brazil','GIG'),
            ('Gilgit','Pakistan','GIL'),
            ('Jijel','Algeria','GJL'),
            ('Grand Junction (CO)','USA','GJT'),
            ('Great Keppel Island','Australia','GKL'),
            ('Glasgow','United Kingdom','GLA'),
            ('Greenville (MS)','USA','GLH'),
            ('Gladstone','Australia','GLT'),
            ('Grenoble','France','GNB'),
            ('Grenada - Point Salines Airport also Maurice Bishop','Grenada','GND'),
            ('Ghent (Gent)','Belgium','GNE'),
            ('Gainesville (FL)','USA','GNV'),
            ('Genoa','Italy','GOA'),
            ('Goa','India','GOI'),
            ('Groton/New London (CT)','USA','GON'),
            ('Goondiwindi','Australia','GOO'),
            ('Gothenburg (Göteborg) - Landvetter','Sweden','GOT'),
            ('Garoua','Cameroon','GOU'),
            ('Gove (Nhulunbuy)','Australia','GOV'),
            ('Gorna','Bulgaria','GOZ'),
            ('Araxos','Greece','GPA'),
            ('Gulfport/Biloxi (MS)','USA','GPT'),
            ('Grand Rapids (MN)','USA','GPZ'),
            ('Green Bay (WI)','USA','GRB'),
            ('George','South Africa','GRJ'),
            ('Gerona','Spain','GRO'),
            ('Groningen - Eelde','Netherlands','GRQ'),
            ('Grand Rapids (MI)','USA','GRR'),
            ('Sao Paulo - Guarulhos International','Brazil','GRU'),
            ('Granada','Spain','GRX'),
            ('Graz','Austria','GRZ'),
            ('Guadalcanal','Solomon Islands','GSI'),
            ('Greensboro/Winston Salem (NC)','USA','GSO'),
            ('Greenville/Spartanburg (SC)','USA','GSP'),
            ('Groote Eylandt - Alyangula','Australia','GTE'),
            ('Great Falls (MT)','USA','GTF'),
            ('Guettin','Germany','GTI'),
            ('Mount Cook','New Zealand','GTN'),
            ('Guatemala City - La Aurora International Airport','Guatemala','GUA'),
            ('Gunnison/Crested Butte (CO)','USA','GUC'),
            ('Hagåtña - Guam International Airport','Guam','GUM'),
            ('Geneva - Geneva-Cointrin International Airport','Switzerland','GVA'),
            ('Gwadar','Pakistan','GWD'),
            ('Gweru','Zimbabwe','GWE'),
            ('Westerland Sylt Airport','Germany','GWT'),
            ('Galway','Ireland','GWY'),
            ('Guayaquil - Simon Bolivar','Ecuador','GYE'),
            ('Goiania Santa Genoveva Airport','Brazil','GYN'),
            ('Gympie','Australia','GYP'),
            ('Gaza City - Gaza International Airport','Palestinian Territory','GZA'),
            ('Gaziantep','Turkey','GZT'),
            ('Hachijo Jima','Japan','HAC'),
            ('Den Haag (The Hague)','Netherlands','HAG'),
            ('Moroni - Prince Said Ibrahim','Comoros (Comores)','HAH'),
            ('Hannover','Germany','HAJ'),
            ('Hamburg - Fuhlsbuettel','Germany','HAM'),
            ('Hanoi - Noi Bai International Airport','Vietnam','HAN'),
            ('Whitsunday Resort','Australia','HAP'),
            ('Harrisburg (PA) - Harrisburg Skyport','USA','HAR'),
            ('Haugesund','Norway','HAU'),
            ('Havana - José Martí International','Cuba','HAV'),
            ('Hobart','Australia','HBA'),
            ('Alexandria - Borg el Arab Airport','Egypt','HBH'),
            ('Hyderabad','Pakistan','HDD'),
            ('Steamboat Springs (CO)','USA','HDN'),
            ('Hatyai (Hat Yai)','Thailand','HDY'),
            ('Helsinki - Vantaa','Finland','HEL'),
            ('Heraklion','Greece','HER'),
            ('Athens Hellinikon Airport','Greece','HEW'),
            ('Haifa','Israel','HFA'),
            ('Hammerfest','Norway','HFT'),
            ('Hangchow (Hangzhou)','Zhejiang PR China','HGH'),
            ('Korhogo','Cote d\'Ivoire','HGO'),
            ('Hilton Head Island (SC)','USA','HHH'),
            ('Frankfurt/Hahn','Germany','HHN'),
            ('Hibbing (MN)','USA','HIB'),
            ('Lake Havasu City (AZ)','USA','HII'),
            ('Hiroshima International','Japan','HIJ'),
            ('Honiara Henderson International','Solomon Islands','HIR'),
            ('Hayman Island','Australia','HIS'),
            ('Hakodate','Japan','HKD'),
            ('Hong Kong - International Airport (HKIA)','Hong Kong','HKG'),
            ('Jackson (MS) - Hawkins Field   ','USA','HKS'),
            ('Phuket','Thailand','HKT'),
            ('Hickory (NC)','USA','HKY'),
            ('Lanseria','South Africa','HLA'),
            ('Ulanhot','PR China','HLH'),
            ('Helena (MT)','USA','HLN'),
            ('Jakarta - Halim Perdana Kusuma','Indonesia','HLP'),
            ('Hamilton','Australia','HLT'),
            ('Hamilton','New Zealand','HLZ'),
            ('Home Hill','Australia','HMH'),
            ('Hermosillo - Gen. Pesqueira Garcia','Mexico','HMO'),
            ('Morioka Hanamaki','Japan','HNA'),
            ('Tokyo - Haneda','Japan','HND'),
            ('Hoonah (AK)','USA','HNH'),
            ('Hinchinbrook Island','Australia','HNK'),
            ('Honolulu (HI) - Honolulu International Airport','USA','HNL'),
            ('Haines (AK)','USA','HNS'),
            ('Holguin','Cuba','HOG'),
            ('Homer (AK)','USA','HOM'),
            ('Huron (SD)','USA','HON'),
            ('Hof','Germany','HOQ'),
            ('Horta','Portugal','HOR'),
            ('Houston (TX)  Hobby','USA','HOU'),
            ('White Plains (NY)','USA','HPN'),
            ('Harbin (Haerbin)','Heilongjiang PR China','HRB'),
            ('Harare - Harare International Airport','Zimbabwe','HRE'),
            ('Hurghada International','Egypt','HRG'),
            ('Kharkov','Ukraine','HRK'),
            ('Harlingen/South Padre Island (TX)','USA','HRL'),
            ('Huntsville (AL)','USA','HSV'),
            ('Chita (Tschita)','Russia','HTA'),
            ('Hamilton Island','Australia','HTI'),
            ('Huntington (WV)','USA','HTS'),
            ('Terre Haute (IN)','USA','HUF'),
            ('Huahine','French Polynesia','HUH'),
            ('Hue - Phu Bai','Viet Nam','HUI'),
            ('Huatulco','Mexico','HUX'),
            ('Humberside','United Kingdom','HUY'),
            ('Hervey Bay','Australia','HVB'),
            ('New Haven (CT)','USA','HVN'),
            ('Havre (MT)','USA','HVR'),
            ('Hwange National Park','Zimbabwe','HWN'),
            ('Hyannis (MA)','USA','HYA'),
            ('Hyderabad - Rajiv Gandhi International Airport','India','HYD'),
            ('Hydaburg (AK)','USA','HYG'),
            ('Washington DC - Dulles International','USA','IAD'),
            ('Niagara Falls International','USA','IAG'),
            ('Houston TX - George Bush Intercontinental Airport','USA','IAH'),
            ('Ibiza','Ibiza/Spain','IBZ'),
            ('Incheon Incheon International Airport','Korea South','ICN'),
            ('Wichita (KS)','USA','ICT'),
            ('Idaho Falls (ID)','USA','IDA'),
            ('Kiev - Zhulhany','Ukraine','IEV'),
            ('Innisfail','Australia','IFL'),
            ('Ingham','Australia','IGH'),
            ('Iguazu Cataratas','Argentina','IGR'),
            ('Jacksonville (IL) - Municipal Airport','USA','IJX'),
            ('Irkutsk','Russia','IKT'),
            ('Killeem (TX)','USA','ILE'),
            ('Iliamna (AK)','USA','ILI'),
            ('Wilmington (NC)','USA','ILM'),
            ('Ile des Pins','New Caledonia','ILP'),
            ('Islay','United Kingdom','ILY'),
            ('Indianapolis (IN) International','USA','IND'),
            ('Nis','Serbia','INI'),
            ('International Falls (MN)','USA','INL'),
            ('Innsbruck - Kranebitten','Austria','INN'),
            ('Inverness','United Kingdom','INV'),
            ('Isle of Man','','IOM'),
            ('Ile Ouen','New Caledonia','IOU'),
            ('Easter Island','Chile','IPC'),
            ('Imperial (CA)','USA','IPL'),
            ('Williamsport (PA)','USA','IPT'),
            ('Iquitos','Peru','IQT'),
            ('Lockhart River','Australia','IRG'),
            ('Biraro','Central African Republic','IRO'),
            ('Mt. Isa','Australia','ISA'),
            ('Islamabad - Benazir Bhutto International Airport','Pakistan','ISB'),
            ('Ishigaki - New Ishigaki Airport','Japan','ISG'),
            ('Williston (ND)','USA','ISL'),
            ('Kingston (NC)','USA','ISO'),
            ('Long Island Islip (NY) - Mac Arthur','USA','ISP'),
            ('Istanbul - Istanbul Atatürk Airport','Turkey','IST'),
            ('Ithaca/Cortland (NY)','USA','ITH'),
            ('Osaka - Itami','Japan','ITM'),
            ('Hilo (HI)','USA','ITO'),
            ('Incercargill','New Zealand','IVC'),
            ('Ivalo','Finland','IVL'),
            ('Bagdogra','India','IXB'),
            ('Chandigarh - Chandigarh International Airport','India','IXC'),
            ('Belgaum','India','IXG'),
            ('Jammu - Satwari','India','IXJ'),
            ('Ranchi','India','IXR'),
            ('Jamshedpur - Sonari Airport','India','IXW'),
            ('Inykern (CA)','USA','IYK'),
            ('Izmir','Turkey','IZM'),
            ('Jalalabad    ','Afghanistan','JAA'),
            ('Jackson Hole (WY)','USA','JAC'),
            ('Jandakot','Australia','JAD'),
            ('Jaffna - Kankesanturai','Sri Lanka','JAF'),
            ('Jacobabad','Pakistan','JAG'),
            ('Jaipur - Sanganeer','India','JAI'),
            ('Jacmel   ','Haiti','JAK'),
            ('Jalapa','Mexico','JAL'),
            ('Jambol','Bulgaria','JAM'),
            ('Jackson (MS) - Jackson Internationall','USA','JAN'),
            ('Jacquinot Bay','Papua New Guinea','JAQ'),
            ('Jauja','Peru','JAU'),
            ('Jacksonville (FL) - International','USA','JAX'),
            ('Jonesboro (AR)  Jonesboro Airport','USA','JBR'),
            ('Joacaba','Brazil','JCB'),
            ('Julia Creek','Australia','JCK'),
            ('Jacobina   ','Brazil','JCM'),
            ('Juiz De Fora - Francisco De Assis Airport','Brazil','JDF'),
            ('Jodhpur','India','JDH'),
            ('Jingdezhen','PR China','JDZ'),
            ('Jeddah - King Abdulaziz International','Saudi Arabia','JED'),
            ('Jeremie - Jeremie Airport','Haiti','JEE'),
            ('Jefferson City (MO) - Jefferson Memorial','USA','JEF'),
            ('Jersey','Channel Islands','JER'),
            ('New York - John F. Kennedy (NY)','USA','JFK'),
            ('Jamnagar - Govardhanpur','India','JGA'),
            ('Jagdalpur','India','JGB'),
            ('Jiayuguan - Jiayuguan Airport','PR China','JGN'),
            ('Ji\'an','Jiangxi China','JGS'),
            ('Johor Bahru - Sultan Ismail International','Malaysia','JHB'),
            ('Helsingborg','Sweden','JHE'),
            ('Jinghong - Gasa Airport','PR China','JHG'),
            ('Kapalua West (HI)','USA','JHM'),
            ('Shute Harbour','Australia','JHQ'),
            ('Jamestown (NY)','USA','JHW'),
            ('Djibouti (city) - Djibouti-Ambouli International Airport','Djibouti','JIB'),
            ('Jijiga','Ethiopia','JIJ'),
            ('Jilin','PR China','JIL'),
            ('Jimma','Ethiopia','JIM'),
            ('Jinja','Uganda','JIN'),
            ('Jipijapa','Ecuador','JIP'),
            ('Jiri','Nepal','JIR'),
            ('Jiujiang - Jiujiang Lushan Airport','PR China','JIU'),
            ('Jiwani','Pakistan','JIW'),
            ('Juanjui','Peru','JJI'),
            ('Jinjiang','PR China','JJN'),
            ('Jönköping (Jonkoping) - Axamo Airport','Sweden','JKG'),
            ('Chios','Greece','JKH'),
            ('Janakpur','Nepal','JKR'),
            ('Jakarta - Metropolitan Area','Indonesia','JKT'),
            ('Jacksonville (TX)','USA','JKV'),
            ('Joplin (MO)','USA','JLN'),
            ('Jalandhar','India','JLR'),
            ('Jales','Brazil','JLS'),
            ('Jamba','Angola','JMB'),
            ('Mykonos','Greece','JMK'),
            ('Jomsom','Nepal','JMO'),
            ('Jamestown (ND)','USA','JMS'),
            ('Jiamusi - Jiamusi Airport','PR China','JMU'),
            ('Januaria','Brazil','JNA'),
            ('Johannesburg - OR Tambo International Airport','South Africa','JNB'),
            ('Jining','PR China','JNG'),
            ('Junin','Argentina','JNI'),
            ('Juneau (AK) - Juneau International Airport','USA','JNU'),
            ('Naxos - Naxos Airport','Greece','JNX'),
            ('Jinzhou - Jinzhou Airport','PR China','JNZ'),
            ('Joensuu','Finland','JOE'),
            ('Joinville - Cubatao Airport','Brazil','JOI'),
            ('Jolo','Philippines','JOL'),
            ('Johnston Island','USA','JON'),
            ('Jos','Nigeria','JOS'),
            ('Joao Pessoa - Castro Pinto Airport','Brazil','JPA'),
            ('Jaque   ','Panama','JQE'),
            ('Jorhat - Rowriah Airport','India','JRH'),
            ('Kilimadjaro','Tanzania','JRO'),
            ('Jerusalem - Atarot Airport (closed)','Israel','JRS'),
            ('Jaisalmer   ','India','JSA'),
            ('Skiathos','Greece','JSI'),
            ('Jose De San Martin','Argentina','JSM'),
            ('Jessore - Jessore Airport','Bangladesh','JSR'),
            ('Johnstown (PA)','USA','JST'),
            ('Jatai','Brazil','JTI'),
            ('Thira','Greece','JTR'),
            ('Juba','South Sudan','JUB'),
            ('Juist (island)','Germany','JUI'),
            ('Jujuy - El Cadillal Airport','Argentina','JUJ'),
            ('Juliaca','Peru','JUL'),
            ('Jumla','Nepal','JUM'),
            ('Jundah','Australia','JUN'),
            ('Juticalpa','Honduras','JUT'),
            ('Upernavik - Upernavik Heliport','Greenland','JUV'),
            ('Janesville (WI) - Rock County','USA','JVL'),
            ('Jwaneng','Botswana','JWA'),
            ('Jackson (MI) - Reynolds Municipal','USA','JXN'),
            ('Jyväskylä (Jyvaskyla)','Finland','JYV'),
            ('Kajaani','Finland','KAJ'),
            ('Kano','Nigeria','KAN'),
            ('Kuusamo','Finland','KAO'),
            ('Kabul - Khwaja Rawash Airport','Afghanistan','KBL'),
            ('Kiev - Borispol','Ukraine','KBP'),
            ('Streaky Bay','Australia','KBY'),
            ('Coffmann Cove (AK)','USA','KCC'),
            ('Collinsville','Australia','KCE'),
            ('Kuching','Malaysia','KCH'),
            ('Kahramanmaras','Turkey','KCM'),
            ('Kochi','Japan','KCZ'),
            ('Khuzdar','Pakistan','KDD'),
            ('Skardu','Pakistan','KDU'),
            ('Reykjavik - Keflavik International','Iceland','KEF'),
            ('Kiel - Holtenau','Germany','KEL'),
            ('Kemi/Tornio','Finland','KEM'),
            ('Kingscote','Australia','KGC'),
            ('Kalgoorlie','Australia','KGI'),
            ('Kigali - Gregoire Kayibanda','Rwanda','KGL'),
            ('Kos','Greece','KGS'),
            ('Kaohsiung International','Taiwan','KHH'),
            ('Karachi - Jinnah International Airport','Pakistan','KHI'),
            ('Kauhajoki','Finland','KHJ'),
            ('Chabarovsk (Khabarovsk)','Russia','KHV'),
            ('Kristianstad','Sweden','KID'),
            ('Niigata','Japan','KIJ'),
            ('Kirkuk','Iraq','KIK'),
            ('Kimberley','South Africa','KIM'),
            ('Kingston - Norman Manley','Jamaica','KIN'),
            ('Kerry County','Ireland','KIR'),
            ('Chisinau - Chişinău International Airport','Moldova','KIV'),
            ('Kitwe','Zambia','KIW'),
            ('Osaka - Kansai International Airport','Japan','KIX'),
            ('Kirkenes','Norway','KKN'),
            ('Kalmar','Sweden','KLR'),
            ('Klagenfurt','Austria','KLU'),
            ('Klawock (AK)','USA','KLW'),
            ('Kalamata','Greece','KLX'),
            ('Kleinsee','South Africa','KLZ'),
            ('Miyazaki','Japan','KMI'),
            ('Kumamoto','Japan','KMJ'),
            ('Keetmanshoop','Namibia','KMP'),
            ('Komatsu','Japan','KMQ'),
            ('Medan - Kualanamu International','Indonesia','KNO'),
            ('King Island','King Island (Australia)','KNS'),
            ('Kanpur','India','KNU'),
            ('Kununurra','Australia','KNX'),
            ('Kona (HI)','USA','KOA'),
            ('Kirkwall (Orkney)','United Kingdom','KOI'),
            ('Kagoshima','Japan','KOJ'),
            ('Kokkola/Pietarsaari','Finland','KOK'),
            ('Karumba','Australia','KRB'),
            ('Krakow (Cracow) - John Paul II International Airport','Poland','KRK'),
            ('Kiruna','Sweden','KRN'),
            ('Karup','Denmark','KRP'),
            ('Kristiansand','Norway','KRS'),
            ('Khartoum - Khartoum International Airport','Sudan','KRT'),
            ('Karlstad','Sweden','KSD'),
            ('Kassala','Sudan','KSL'),
            ('Kristiansund','Norway','KSU'),
            ('Karratha','Australia','KTA'),
            ('Thorne Bay (AK)','USA','KTB'),
            ('Kathmandu - Tribhuvan International Airport','Nepal','KTM'),
            ('Ketchikan (AK)','USA','KTN'),
            ('Katherine','Australia','KTR'),
            ('Kittilä','Finland','KTT'),
            ('Kuantan','Malaysia','KUA'),
            ('Kushiro','Japan','KUH'),
            ('Kuala Lumpur - International Airport','Malaysia','KUL'),
            ('Kuopio','Finland','KUO'),
            ('Kavalla','Greece','KVA'),
            ('Kuwait - Kuwait International','Kuwait','KWI'),
            ('Guilin - Liangjiang','Guangxi PR China','KWL'),
            ('Kowanyama','Australia','KWM'),
            ('Konya','Turkey','KYA'),
            ('Kars','Turkey','KYS'),
            ('Kazan (Ka San)','Russia','KZN'),
            ('Luanda - 4 de Fevereiro','Angola','LAD'),
            ('Lae - Lae Nadzab Airport','Papua New Guinea','LAE'),
            ('Lafayette (IN)','USA','LAF'),
            ('Lannion','France','LAI'),
            ('Lansing (MI)','USA','LAN'),
            ('La Paz - Leon','Mexico','LAP'),
            ('Laramie (WY)','USA','LAR'),
            ('Las Vegas (NV)','USA','LAS'),
            ('Lawton (OK)','USA','LAW'),
            ('Los Angeles (CA) - International','USA','LAX'),
            ('Leeds/Bradford','United Kingdom','LBA'),
            ('Lubbock (TX)','USA','LBB'),
            ('Latrobe (PA)','USA','LBE'),
            ('Paris - Le Bourget','France','LBG'),
            ('Albi','France','LBI'),
            ('Lambarene','Gabon','LBQ'),
            ('Labuan','Malaysia','LBU'),
            ('Libreville','Gabon','LBV'),
            ('Larnaca','Cyprus','LCA'),
            ('La Coruna','Spain','LCG'),
            ('Lake Charles (LA)','USA','LCH'),
            ('London - City Airport','United Kingdom','LCY'),
            ('Lindeman Island','Australia','LDC'),
            ('Lourdes/Tarbes','France','LDE'),
            ('Lidkoeping','Sweden','LDK'),
            ('Derry (Londonderry)','United Kingdom','LDY'),
            ('Learmouth (Exmouth)','Australia','LEA'),
            ('Lebanon (NH)','USA','LEB'),
            ('St. Petersburg (Leningrad) - Pulkovo','Russia','LED'),
            ('Almeria','Spain','LEI'),
            ('Leipzig','Germany','LEJ'),
            ('Labe','Guinea','LEK'),
            ('Land\'s End','United Kingdom','LEQ'),
            ('Leinster','Australia','LER'),
            ('Lexington (KY)','USA','LEX'),
            ('Lelystad','Netherlands','LEY'),
            ('Lafayette La','USA','LFT'),
            ('Lome','Togo','LFW'),
            ('New York - LaGuardia (NY)','USA','LGA'),
            ('Long Beach (CA)','USA','LGB'),
            ('Liege','Belgium','LGG'),
            ('Langkawi (islands)','Malaysia','LGK'),
            ('London - Gatwick','United Kingdom','LGW'),
            ('Lahore','Pakistan','LHE'),
            ('London - Heathrow','United Kingdom','LHR'),
            ('Lifou','Loyaute Pazifik','LIF'),
            ('Limoges','France','LIG'),
            ('Lihue (HI)','USA','LIH'),
            ('Long Island (AK)','USA','LIJ'),
            ('Lille','France','LIL'),
            ('Lima - J Chavez International','Peru','LIM'),
            ('Milan - Linate','Italy','LIN'),
            ('Lisala','Congo (DRC)','LIQ'),
            ('Lisbon - Lisboa','Portugal','LIS'),
            ('Little Rock (AR)','USA','LIT'),
            ('Ljubljana - Brnik','Slovenia','LJU'),
            ('Lakselv','Norway','LKL'),
            ('Lucknow','India','LKO'),
            ('Lulea','Sweden','LLA'),
            ('Lilongwe - Lilongwe International','Malawi','LLW'),
            ('Los Mochis','Mexico','LMM'),
            ('Lampedusa','Italy','LMP'),
            ('Klamath Fall (OR)','USA','LMT'),
            ('Lincoln (NE)','USA','LNK'),
            ('Leonora','Australia','LNO'),
            ('Lancaster (PA)','USA','LNS'),
            ('Lanai City (HI)','USA','LNY'),
            ('Linz - Hoersching','Austria','LNZ'),
            ('London Metropolitan Area','United Kingdom','LON'),
            ('Lagos - Murtala Muhammed','Nigeria','LOS'),
            ('Las Palmas','Spain','LPA'),
            ('La Paz - El Alto','Bolivia','LPB'),
            ('Liverpool','United Kingdom','LPL'),
            ('Lappeenranta','Finland','LPP'),
            ('Laredo (TX)','USA','LRD'),
            ('Longreach','Australia','LRE'),
            ('Jacksonville (AR)  Little Rock AFB   ','USA','LRF'),
            ('La Rochelle','France','LRH'),
            ('La Romana - La Romana International Airport','Dominican Republic','LRM'),
            ('Lorient','France','LRT'),
            ('La Crosse (WI)','USA','LSE'),
            ('Sumburgh (Shetland)','United Kingdom','LSI'),
            ('Launceston','Australia','LST'),
            ('Lismore','Australia','LSY'),
            ('Losinj - Losinj Arpt','Croatia (Hrvatska)','LSZ'),
            ('London - Luton','United Kingdom','LTN'),
            ('Loreto','Mexico','LTO'),
            ('Luederitz','Namibia','LUD'),
            ('Lugano','Switzerland','LUG'),
            ('Lusisiki','South Africa','LUJ'),
            ('Luxi - Mangshi','Yunnan PR China','LUM'),
            ('Lusaka - Lusaka International Airport','Zambia','LUN'),
            ('Luxembourg','Luxembourg','LUX'),
            ('Laverton','Australia','LVO'),
            ('Greenbrier/Lewisburg (WV)','USA','LWB'),
            ('Lerwick/Tingwall (Shetland Islands)','United Kingdom','LWK'),
            ('Lvov (Lwow Lemberg)','Ukraine','LWO'),
            ('Lewiston (ID)','USA','LWS'),
            ('Lewistown (MT)','USA','LWT'),
            ('Luxor','Egypt','LXR'),
            ('Lynchburg (VA)','USA','LYH'),
            ('Lyon - Bron','France','LYN'),
            ('Lyons (KS) - Rice County Municipal','USA','LYO'),
            ('Faisalabad','Pakistan','LYP'),
            ('Longyearbyen - Svalbard','Svalbard/Norway','LYR'),
            ('Lyon - Satolas','France','LYS'),
            ('Lydd - Lydd International Airport','United Kingdom','LYX'),
            ('Lazaro Cardenas','Mexico','LZC'),
            ('Lizard Island','Australia','LZR'),
            ('Chennai (Madras)','India','MAA'),
            ('Madrid - Barajas','Spain','MAD'),
            ('Midland/Odessa (TX)','USA','MAF'),
            ('Mahon','Spain','MAH'),
            ('Manchester','United Kingdom','MAN'),
            ('Manaus - Eduardo Gomes International Airport','Brazil','MAO'),
            ('Maracaibo - La Chinita','Venezuela','MAR'),
            ('Maupiti','French Polynesia','MAU'),
            ('Mayaguez','Puerto Rico','MAZ'),
            ('Mombasa - Moi International','Kenya','MBA'),
            ('Maryborough','Australia','MBH'),
            ('Montego Bay - Sangster International','Jamaica','MBJ'),
            ('Mkambati','South Africa','MBM'),
            ('Saginaw/Bay City/Midland (MI)','USA','MBS'),
            ('Maribor','Slovenia','MBX'),
            ('Merced (CA)','USA','MCE'),
            ('Kansas City (MO) - Kansas City International Airport','USA','MCI'),
            ('Mt. McKinley (AK)','USA','MCL'),
            ('Macon (GA)','USA','MCN'),
            ('Orlando - International Airport (FL)','USA','MCO'),
            ('Macapa - Alberto Alcolumbre International Airport','Brazil','MCP'),
            ('Muscat - Seeb','Oman','MCT'),
            ('Mason City IA','USA','MCW'),
            ('Sunshine Coast','Australia','MCY'),
            ('Maceio - Zumbi dos Palmares International Airport','Brazil','MCZ'),
            ('Manado','Indonesia','MDC'),
            ('Medellin','Colombia','MDE'),
            ('Mandalay - Annisaton','Myanmar','MDL'),
            ('Mar del Plata','Argentina','MDQ'),
            ('Harrisburg (PA) - Harrisburg International','USA','MDT'),
            ('Chicago (IL) Midway','USA','MDW'),
            ('Midway Island - Sand Island Field','US Minor Outlying Islands','MDY'),
            ('Mendoza','Argentina','MDZ'),
            ('Medina','Saudi Arabia','MED'),
            ('Mare','New Caledonia','MEE'),
            ('Meridian (MS)','USA','MEI'),
            ('Melbourne - Tullamarine','Australia','MEL'),
            ('Memphis (TN)','USA','MEM'),
            ('Medan - Polania Int\'l (now Soewondo AFB)','Indonesia','MES'),
            ('Mexico City - Juarez International','Mexico','MEX'),
            ('Messina','South Africa','MEZ'),
            ('McAllen (TX)','USA','MFE'),
            ('Moanda','Gabon','MFF'),
            ('Muzaffarabad','Pakistan','MFG'),
            ('Macau','Macau China SAR','MFM'),
            ('Milford Sound','New Zealand','MFN'),
            ('Manguna','Papua New Guinea','MFO'),
            ('Maradi','Niger','MFQ'),
            ('Medford (OR)','USA','MFR'),
            ('Mfuwe','Zambia','MFU'),
            ('Managua - Augusto C Sandino','Nicaragua','MGA'),
            ('Mount Gambier','Australia','MGB'),
            ('Margate','South Africa','MGH'),
            ('Montgomery (AL)','USA','MGM'),
            ('Mogadishu','Somalia','MGQ'),
            ('Morgantown (WV)','USA','MGW'),
            ('Mitchell (SD)','USA','MHE'),
            ('Marsh Harbour','Bahamas','MHH'),
            ('Mariehamn (Maarianhamina)','Finland','MHQ'),
            ('Manchester (NH)','USA','MHT'),
            ('Miami (FL)','USA','MIA'),
            ('Merida','Mexico','MID'),
            ('Mikkeli','Finland','MIK'),
            ('Milan','Italy','MIL'),
            ('Merimbula','Australia','MIM'),
            ('Monastir','Tunisia','MIR'),
            ('Man','Cote d\'Ivoire','MJC'),
            ('Moenjodaro','Pakistan','MJD'),
            ('Mouila','Gabon','MJL'),
            ('Majunga','Madagascar','MJN'),
            ('Jackson  MN  ','USA','MJQ'),
            ('Mytilene (Lesbos)','Greece','MJT'),
            ('Murcia','Spain','MJV'),
            ('Milwaukee (WI)','USA','MKE'),
            ('Muskegon (MI)','USA','MKG'),
            ('Kaunakakai (HI)','USA','MKK'),
            ('Jackson (TN) - Mckellar','USA','MKL'),
            ('Meekatharra','Australia','MKR'),
            ('Mackay','Australia','MKY'),
            ('Luga','Malta','MLA'),
            ('Melbourne (FL)','USA','MLB'),
            ('Male - International','Maledives','MLE'),
            ('Mulhouse','France','MLH'),
            ('Moline/Quad Cities (IL)','USA','MLI'),
            ('Morelia','Mexico','MLM'),
            ('Miles City (MT)','USA','MLS'),
            ('Monroe La','USA','MLU'),
            ('Monrovia - Metropolitan Area','Liberia','MLW'),
            ('Malatya','Turkey','MLX'),
            ('Malmo (Malmoe)','Sweden','MMA'),
            ('Teesside Durham Tees Valley','United Kingdom','MME'),
            ('Mount Magnet','Australia','MMG'),
            ('Matsumoto Nagano','Japan','MMJ'),
            ('Murmansk','Russia','MMK'),
            ('Middlemount','Australia','MMM'),
            ('Malmo (Malmö) - Malmö Airport','Sweden','MMX'),
            ('Miyako Jima (Ryuku Islands) - Hirara','Japan','MMY'),
            ('Manila - Ninoy Aquino International','Philippines','MNL'),
            ('Mobile (AL) - Pascagoula (MS)','USA','MOB'),
            ('Modesto (CA)','USA','MOD'),
            ('Minot (ND)','USA','MOT'),
            ('Moranbah','Australia','MOV'),
            ('Moscow - Metropolitan Area','Russia','MOW'),
            ('Moorea','French Polynesia','MOZ'),
            ('Katima Mulilo/Mpacha','Namibia','MPA'),
            ('Sindhri','Pakistan','MPD'),
            ('Montpellier - Frejorgues','France','MPL'),
            ('Maputo - Maputo International','Mozambique','MPM'),
            ('Mildura','Australia','MQL'),
            ('Mardin','Turkey','MQM'),
            ('Nelspruit - Kruger Mpumalanga International Airport','South Africa','MQP'),
            ('Moundou','Chad','MQQ'),
            ('Marquette (MI)','USA','MQT'),
            ('Martinsburg (WV)','USA','MRB'),
            ('Marseille','France','MRS'),
            ('Mauritius - S.Seewoosagur Ram International','Mauritius','MRU'),
            ('Mineralnye Vody','Russia','MRV'),
            ('Monterey (CA)','USA','MRY'),
            ('Moree','Australia','MRZ'),
            ('Kent (Manston) Kent International','United Kingdom','MSE'),
            ('Muscle Shoals (AL)','USA','MSL'),
            ('Madison (WI)','USA','MSN'),
            ('Missula (MT)','USA','MSO'),
            ('Minneapolis - St. Paul International Airport (MN)','USA','MSP'),
            ('Minsk International','Belarus','MSQ'),
            ('Mus','Turkey','MSR'),
            ('Maastricht/Aachen','Netherlands','MST'),
            ('Maseru - Moshoeshoe International','Lesotho','MSU'),
            ('New Orleans La','USA','MSY'),
            ('Marathon (FL)','USA','MTH'),
            ('Montrose/Tellruide (CO)','USA','MTJ'),
            ('Maitland','Australia','MTL'),
            ('Metlakatla (AK)','USA','MTM'),
            ('Mattoon (IL)','USA','MTO'),
            ('Manzini - Matsapha International','Swaziland','MTS'),
            ('Minatitlan','Mexico','MTT'),
            ('Monterrey - Gen. Mariano Escobedo','Mexico','MTY'),
            ('Maun','Botswana','MUB'),
            ('Muenchen (Munich) - Franz Josef Strauss','Germany','MUC'),
            ('Kamuela (HI)','USA','MUE'),
            ('Marsa Matrah (Marsa Matruh)','Egypt','MUH'),
            ('Multan','Pakistan','MUX'),
            ('Mvengue','Gabon','MVB'),
            ('Montevideo - Carrasco','Uruguay','MVD'),
            ('Maroua','Cameroon','MVR'),
            ('Martha\'s Vineyard (MA)','USA','MVY'),
            ('Masvingo','Zimbabwe','MVZ'),
            ('Mianwali','Pakistan','MWD'),
            ('Moses Lake (WA)','USA','MWH'),
            ('Mexicali','Mexico','MXL'),
            ('Milan - Malpensa','Italy','MXP'),
            ('Moruya','Australia','MYA'),
            ('Malindi','Kenya','MYD'),
            ('Matsuyama','Japan','MYJ'),
            ('Mysore','India','MYQ'),
            ('Myrtle Beach (SC) - Myrtle Beach AFB','USA','MYR'),
            ('Miri','Malaysia','MYY'),
            ('Mzamba','South Africa','MZF'),
            ('Makung','Taiwan','MZG'),
            ('Metz -  Frescaty','France','MZM'),
            ('Mazatlan','Mexico','MZT'),
            ('Mossel Bay','South Africa','MZY'),
            ('Narrabri','Australia','NAA'),
            ('Nagpur','India','NAG'),
            ('Nakhichevan','Azerbaijan','NAJ'),
            ('Nadi','Fiji','NAN'),
            ('Naples','Italy','NAP'),
            ('Bahamas - Lynden Pindling International Airport','The Bahamas','NAS'),
            ('Natal - Augusto Severo International Airport','Brazil','NAT'),
            ('Beijing - Nanyuan Airport','China','NAY'),
            ('Nairobi','Kenya','NBO'),
            ('Nice - Cote D\'Azur','France','NCE'),
            ('Newcastle','United Kingdom','NCL'),
            ('Newcastle','South Africa','NCS'),
            ('Annecy','France','NCY'),
            ('Nouadhibou','Mauritania','NDB'),
            ('N\'Djamena','Chad','NDJ'),
            ('Rundu','Namibia','NDU'),
            ('Nevis','St. Kitts and Nevis','NEV'),
            ('N\'Gaoundere','Cameroon','NGE'),
            ('Nagoya - Komaki AFB','Japan','NGO'),
            ('Nagasaki','Japan','NGS'),
            ('Nicosia','Cyprus','NIC'),
            ('Niamey','Niger','NIM'),
            ('Jacksonville (FL) Jacksonville NAS   ','USA','NIP'),
            ('Nouakchott','Mauritania','NKC'),
            ('N\'Dola','Zambia','NLA'),
            ('Nuevo Laredo','Mexico','NLD'),
            ('Norfolk Island','Australia','NLK'),
            ('Nelspruit','South Africa','NLP'),
            ('Mexico City - Santa Lucia','Mexico','NLU'),
            ('Nikolaev','Ukraine','NLV'),
            ('Nanning','Guangxi PR China','NNG'),
            ('Knock','Ireland','NOC'),
            ('Mactan Island - Nab','Philippines','NOP'),
            ('Noumea','New Caledonia','NOU'),
            ('Newquay','United Kingdom','NQY'),
            ('Narrandera','Australia','NRA'),
            ('Norrkoeping','Sweden','NRK'),
            ('Tokyo - Narita','Japan','NRT'),
            ('Noosa','Australia','NSA'),
            ('Nelson','New Zealand','NSN'),
            ('Scone','Australia','NSO'),
            ('Nakhon Si Thammarat','Thailand','NST'),
            ('Nantes - Nantes Atlantique Airport','France','NTE'),
            ('Newcastle - Williamtown','Australia','NTL'),
            ('Monterrey - Aeropuerto Del Norte','Mexico','NTR'),
            ('Pilanesberg/Sun City','South Africa','NTY'),
            ('Nürnberg (Nuremberg)','Germany','NUE'),
            ('Norwich','United Kingdom','NWI'),
            ('New York (NY)','USA','NYC'),
            ('Jacksonville (FL) - Cecil Field NAS   ','USA','NZC'),
            ('Orange','Australia','OAG'),
            ('Jacksonville (NC)','USA','OAJ'),
            ('Oakland (CA)','USA','OAK'),
            ('Oaxaca - Xoxocotlan','Mexico','OAX'),
            ('Ouadda','Central African Republic','ODA'),
            ('Cordoba','Spain','ODB'),
            ('Odense','Denmark','ODE'),
            ('Odessa','Ukraine','ODS'),
            ('Kahului (HI)','USA','OGG'),
            ('Ohrid','Macedonia','OHD'),
            ('Kohat','Pakistan','OHT'),
            ('Oita','Japan','OIT'),
            ('Okinawa Ryukyo Island - Naha','Japan','OKA'),
            ('Oklahoma City (OK) - Will Rogers World','USA','OKC'),
            ('Sapporo - Okadama','Hokkaido Japan','OKD'),
            ('Okayama','Japan','OKJ'),
            ('Mokuti','Namibia','OKU'),
            ('Olbia','Italy','OLB'),
            ('Wolf Point (MT)','USA','OLF'),
            ('Olympic Dam','Australia','OLP'),
            ('Omaha (NE)','USA','OMA'),
            ('Oranjemund','Namibia','OMD'),
            ('Nome (AK)','USA','OME'),
            ('Urmiehm (Orumieh)','Iran','OMH'),
            ('Mostar','Bosnia and Herzegovina','OMO'),
            ('Ondangwa','Namibia','OND'),
            ('Ontario (CA)','USA','ONT'),
            ('Gold Coast','Australia','OOL'),
            ('Cooma','Australia','OOM'),
            ('Porto','Portugal','OPO'),
            ('Oerebro','Sweden','ORB'),
            ('Chicago (IL) O\'Hare International Airport','USA','ORD'),
            ('Norfolk/Virginia Beach (VA)','USA','ORF'),
            ('Worcester (MA)','USA','ORH'),
            ('Cork','Ireland','ORK'),
            ('Orlando Metropolitan Area (FL)','USA','ORL'),
            ('Oran (Ouahran)','Algeria','ORN'),
            ('Orpheus Island','Australia','ORS'),
            ('Paris - Orly','France','ORY'),
            ('Osaka Metropolitan Area','Japan','OSA'),
            ('Oshkosh (WI)','USA','OSH'),
            ('Osijek','Croatia (Hrvatska)','OSI'),
            ('Oslo - Oslo Airport Gardermoen','Norway','OSL'),
            ('Mosul','Iraq','OSM'),
            ('North Bend (OR)','USA','OTH'),
            ('Bucharest - Henri Coandă International Airport','Romania','OTP'),
            ('Kotzbue (AK)','USA','OTZ'),
            ('Ouagadougou','Burkina Faso','OUA'),
            ('Oujda','Morocco','OUD'),
            ('Oudtshoorn','South Africa','OUH'),
            ('Out Skerries (Shetland)','United Kingdom','OUK'),
            ('Oulu','Finland','OUL'),
            ('Zouerate','Mauritania','OUZ'),
            ('Novosibirsk - Tolmachevo','Russia','OVB'),
            ('Oviedo','Spain','OVD'),
            ('Owensboro (KY)','USA','OWB'),
            ('Oxnard (CA)','USA','OXR'),
            ('Ouarzazate','Morocco','OZZ'),
            ('Paderborn/Lippstadt','Germany','PAD'),
            ('Paducah (KY)','USA','PAH'),
            ('Port au Prince','Haiti','PAP'),
            ('Paris','France','PAR'),
            ('Patna','India','PAT'),
            ('Puebla','Mexico','PBC'),
            ('Paro','Bhutan','PBH'),
            ('West Palm Beach (FL)','USA','PBI'),
            ('Paramaribo - Zanderij International','Suriname','PBM'),
            ('Paraburdoo','Australia','PBO'),
            ('Plettenberg Bay','South Africa','PBZ'),
            ('Ponta Delgada','Portugal','PDL'),
            ('Pendelton (OR)','USA','PDT'),
            ('Portland International (OR)','USA','PDX'),
            ('Perugia','Italy','PEG'),
            ('Pereira','Colombia','PEI'),
            ('Beijing','China','PEK'),
            ('Penang International','Malaysia','PEN'),
            ('Perth International','Australia','PER'),
            ('Peshawar','Pakistan','PEW'),
            ('Panama City (FL)','USA','PFN'),
            ('Paphos','Cyprus','PFO'),
            ('Page/Lake Powell (AZ)','USA','PGA'),
            ('Perpignan','France','PGF'),
            ('Greenville (NC)','USA','PGV'),
            ('Port Harcourt','Nigeria','PHC'),
            ('Port Hedland','Australia','PHE'),
            ('Newport News/Williamsburg (VA)','USA','PHF'),
            ('Philadelphia (PA) - International','USA','PHL'),
            ('Phalaborwa','South Africa','PHW'),
            ('Phoenix (AZ) - Sky Harbor International','USA','PHX'),
            ('Peoria/Bloomington (IL)','USA','PIA'),
            ('Laurel/Hattisburg (MS)','USA','PIB'),
            ('Pocatello (ID)','USA','PIH'),
            ('Glasgow Prestwick','United Kingdom','PIK'),
            ('Pierre (SD)','USA','PIR'),
            ('Poitiers - Biard','France','PIS'),
            ('Pittsburgh International Airport (PA)','USA','PIT'),
            ('Panjgur','Pakistan','PJG'),
            ('Pakersburg (WV) /Marietta (OH)','USA','PKB'),
            ('Selibi Phikwe','Botswana','PKW'),
            ('Plattsburgh (NY)','USA','PLB'),
            ('Pellston (MI)','USA','PLN'),
            ('Port Lincoln','Australia','PLO'),
            ('Port Elizabeth','South Africa','PLZ'),
            ('Palmdale/Lancaster (CA)','USA','PMD'),
            ('Palma de Mallorca','Spain','PMI'),
            ('Palermo - Punta Raisi','Italy','PMO'),
            ('Palmerston North','New Zealand','PMR'),
            ('Margerita','Venezuela','PMV'),
            ('Palmas','Brazil','PMW'),
            ('Phnom Penh - Pochentong','Cambodia','PNH'),
            ('Pohnpei','Micronesia','PNI'),
            ('Pantelleria','Italy','PNL'),
            ('Pune','India Maharashtra','PNQ'),
            ('Pointe Noire','Congo (ROC)','PNR'),
            ('Pensacola (FL)','USA','PNS'),
            ('Porto Alegre - Salgado Filho International Airport','Brazil','POA'),
            ('Port Gentil','Gabon','POG'),
            ('Port Moresby - Jackson Field','Papua New Guinea','POM'),
            ('Puerto Plata','Dominican Republic','POP'),
            ('Pori','Finland','POR'),
            ('Port of Spain - Piarco International','Trinidad and Tobago','POS'),
            ('Poughkeepsie (NY)','USA','POU'),
            ('Poznan Lawica','Poland','POZ'),
            ('Pago Pago','American Samoa','PPG'),
            ('Prosperpine','Australia','PPP'),
            ('Papeete - Faaa','French Polynesia (Tahiti)','PPT'),
            ('Presque Island (ME)','USA','PQI'),
            ('Port Macquarie','Australia','PQQ'),
            ('Prague - Ruzyne','Czech Republic','PRG'),
            ('Pristina','Serbia','PRN'),
            ('Pretoria - Wonderboom Apt.','South Africa','PRY'),
            ('Pisa - Galileo Galilei','Italy','PSA'),
            ('Pasco (WA)','USA','PSC'),
            ('Port Said','Egypt','PSD'),
            ('Ponce','Puerto Rico','PSE'),
            ('Petersburg (AK)','USA','PSG'),
            ('Pasni','Pakistan','PSI'),
            ('Palm Springs (CA)','USA','PSP'),
            ('Pescara','Italy','PSR'),
            ('Pietersburg','South Africa','PTG'),
            ('Portland','Australia','PTJ'),
            ('Basse-Terre - Pointe-à-Pitre International Airport','Guadeloupe','PTP'),
            ('Panama City - Tocumen International','Panama','PTY'),
            ('Pueblo (CO)','USA','PUB'),
            ('Pau','France','PUF'),
            ('Port Augusta','Australia','PUG'),
            ('Punta Cana - Punta Cana International','Dominican Republic','PUJ'),
            ('Punta Arenas - Presidente Carlos Ibáñez del Campo','Chile','PUQ'),
            ('Pu San (Busan) - Gimhae International Airport','South Korea','PUS'),
            ('Pullman (WA)','USA','PUW'),
            ('Pula','Croatia (Hrvatska)','PUY'),
            ('Providence (RI)','USA','PVD'),
            ('Shanghai - Pu Dong','China','PVG'),
            ('Porto Velho','Brazil','PVH'),
            ('Preveza/Lefkas','Greece','PVK'),
            ('Puerto Vallarta','Mexico','PVR'),
            ('Portland (ME)','USA','PWM'),
            ('Puerto Escondido','Mexico','PXM'),
            ('Porto Santo','Portugal','PXO'),
            ('Jeypore - Jeypore Airport','India','PYB'),
            ('Pattaya','Thailand','PYX'),
            ('Pietermaritzburg','South Africa','PZB'),
            ('Zhob','Pakistan','PZH'),
            ('Puerto Ordaz','Venezuela','PZO'),
            ('Chiba City','Japan','QCB'),
            ('Montenegro','Brazil','QGF'),
            ('Limassol','Cyprus','QLI'),
            ('Mirpur','Pakistan','QML'),
            ('Anand','India','QNB'),
            ('Novi Sad','Serbia','QND'),
            ('Singapore - Paya Lebar','Singapore','QPG'),
            ('Tallinn - Pirita Harbour','Estonia','QUF'),
            ('Praia','Cape Verde','RAI'),
            ('Rajkot','India','RAJ'),
            ('Marrakesh - Menara Airport','Morocco','RAK'),
            ('Rapid City (SD)','USA','RAP'),
            ('Rarotonga','Cook Island','RAR'),
            ('Rawala Kot','Pakistan','RAZ'),
            ('Rabat - Sale','Morocco','RBA'),
            ('Rio Branco - Plácido de Castro International Airport','Brazil','RBR'),
            ('Richards Bay','South Africa','RCB'),
            ('Redding (CA)','USA','RDD'),
            ('Reading (PA)','USA','RDG'),
            ('Redmond (OR)','USA','RDM'),
            ('Raleigh/Durham (NC)','USA','RDU'),
            ('Rodez','France','RDZ'),
            ('Recife - Guararapes-Gilberto Freyre International','Brazil','REC'),
            ('Reggio Calabria','Italy','REG'),
            ('Reykjavik - Metropolitan Area','Iceland','REK'),
            ('Reus','Spain','REU'),
            ('Rockford (IL)','USA','RFD'),
            ('Raiatea','French Polynesia','RFP'),
            ('Rangiroa','French Polynesia','RGI'),
            ('Rangoon (Yangon) - Mingaladon','Myanmar','RGN'),
            ('Rhinelander (WI)','USA','RHI'),
            ('Rhodos','Greece','RHO'),
            ('Richmond (VA)','USA','RIC'),
            ('Rio de Janeiro','Brazil','RIO'),
            ('Riga','Latvia','RIX'),
            ('Rijeka','Croatia (Hrvatska)','RJK'),
            ('Rockland (ME)','USA','RKD'),
            ('Rock Springs (WY)','USA','RKS'),
            ('Ras al Khaymah (Ras al Khaimah)','United Arab Emirates','RKT'),
            ('Arlit','Niger','RLT'),
            ('Marsa Alam','Egypt','RMF'),
            ('Rimini','Italy','RMI'),
            ('Ronneby','Sweden','RNB'),
            ('Roanne','France','RNE'),
            ('Roenne','Denmark','RNN'),
            ('Reno (NV)','USA','RNO'),
            ('Rennes','France','RNS'),
            ('Roanoke (VA)','USA','ROA'),
            ('Monrovia - Roberts International','Liberia','ROB'),
            ('Rochester (NY)','USA','ROC'),
            ('Rockhampton','Australia','ROK'),
            ('Rome','Italy','ROM'),
            ('Rosario','Argentina','ROS'),
            ('Rotorua','New Zealand','ROT'),
            ('Ruse','Bulgaria','ROU'),
            ('Rodrigues Island','Mauritius','RRG'),
            ('Santa Rosa','Argentina','RSA'),
            ('Rock Sound','Bahamas','RSD'),
            ('Rochester (MN)','USA','RST'),
            ('Fort Myers Southwest Florida Reg (FL)','USA','RSW'),
            ('Roatan','Honduras','RTB'),
            ('Rotterdam','Netherlands','RTM'),
            ('Riyadh - King Khaled International','Saudi Arabia','RUH'),
            ('Saint Denis de la Reunion','Reunion','RUN'),
            ('Rovaniemi','Finland','RVN'),
            ('Rocky Mount - Wilson (NC)','USA','RWI'),
            ('Rawalpindi','Pakistan','RWP'),
            ('Rahim Yar Khan','Pakistan','RYK'),
            ('Sanaa (Sana\'a) - Sana\'a International','Yemen','SAH'),
            ('San Salvador','El Salvador','SAL'),
            ('San Diego - Lindberg Field International (CA)','USA','SAN'),
            ('Sao Paulo','Brazil','SAO'),
            ('San Pedro Sula','Honduras','SAP'),
            ('San Antonio (TX)','USA','SAT'),
            ('Savannah (GA)','USA','SAV'),
            ('Istanbul - Sabiha Gokcen','Turkey','SAW'),
            ('Salisbury','Zimbabwe','SAY'),
            ('Santa Barbara (CA)','USA','SBA'),
            ('Saint Brieuc','France','SBK'),
            ('South Bend (IN)','USA','SBN'),
            ('San Luis Obisco (CA)','USA','SBP'),
            ('Springbok','South Africa','SBU'),
            ('Sibu','Malaysia','SBW'),
            ('Salisbury (MD)','USA','SBY'),
            ('Prudhoe Bay (AK)','USA','SCC'),
            ('State College/Belefonte (PA)','USA','SCE'),
            ('Scottsdale (AZ)','USA','SCF'),
            ('Stockton (CA)','USA','SCK'),
            ('Santiago de Chile - Arturo Merino Benitez','Chile','SCL'),
            ('Saarbruecken','Germany','SCN'),
            ('Santiago de Compostela','Spain','SCQ'),
            ('Santiago - Antonio Maceo Airport','Cuba','SCU'),
            ('Louisville (KY)','USA','SDF'),
            ('Santa Rosa Copan','Honduras','SDH'),
            ('Sendai','Japan','SDJ'),
            ('Sundsvall','Sweden','SDL'),
            ('Santo Domingo','Dominican Republic','SDQ'),
            ('Santander','Spain','SDR'),
            ('Sado Shima','Japan','SDS'),
            ('Saidu Sharif','Pakistan','SDT'),
            ('Rio de Janeiro - Santos Dumont','Brazil','SDU'),
            ('Sidney (MT)','USA','SDY'),
            ('Seattle/Tacoma (WA)','USA','SEA'),
            ('Sehba','Libya','SEB'),
            ('Seoul - Kimpo','South Korea','SEL'),
            ('Southend (London)','United Kingdom','SEN'),
            ('Siwa','Egypt','SEW'),
            ('Mahe - Seychelles International','Seychelles','SEZ'),
            ('Sfax','Tunisia','SFA'),
            ('St. Martin','St. Martin (Guadeloupe)','SFG'),
            ('Soendre Stroemfjord','Greenland','SFJ'),
            ('San Francisco - International Airport SA','USA','SFO'),
            ('Soenderborg','Denmark','SGD'),
            ('Springfield (MO)','USA','SGF'),
            ('Ho Chi Minh City (Saigon) - Tan Son Nhat International','Viet Nam','SGN'),
            ('St. George (UT)','USA','SGU'),
            ('Skagway (AK)','USA','SGY'),
            ('Shanghai - Hongqiao','China','SHA'),
            ('Shenandoah Valley/Stauton (VA)','USA','SHD'),
            ('Shenyang','Liaoning PR China','SHE'),
            ('Sharjah','United Arab Emirates','SHJ'),
            ('Sheridan (WY)','USA','SHR'),
            ('Shreveport La','USA','SHV'),
            ('Sal','Cape Verde','SID'),
            ('Singapore - Changi','Singapore','SIN'),
            ('Simferopol','Ukraine','SIP'),
            ('Sishen','South Africa','SIS'),
            ('Sitka (AK)','USA','SIT'),
            ('Singleton','Australia','SIX'),
            ('San Jose (CA)','USA','SJC'),
            ('Los Cabos','Mexico','SJD'),
            ('Sarajevo','Bosnia and Herzegovina','SJJ'),
            ('San Jose','Costa Rica','SJO'),
            ('San Angelo (TX)','USA','SJT'),
            ('San Juan','Puerto Rico','SJU'),
            ('Seinaejoki','Finland','SJY'),
            ('Basseterre - Robert L. Bradshaw International Airport','Saint Kitts and Nevis','SKB'),
            ('Samarkand','Uzbekistan','SKD'),
            ('Saloniki','Greece','SKG'),
            ('Skopje','Macedonia','SKP'),
            ('Skrydstrup','Denmark','SKS'),
            ('Santa Katarina - Mount Sinai','Egypt','SKV'),
            ('Sukkur','Pakistan','SKZ'),
            ('Salta Gen Belgrano','Argentina','SLA'),
            ('Salt Lake City (UT)','USA','SLC'),
            ('Salem (OR)','USA','SLE'),
            ('Salalah','Oman','SLL'),
            ('San Luis Potosi','Mexico','SLP'),
            ('Silistra','Bulgaria','SLS'),
            ('Castries - George F. L. Charles Airport','Saint Lucia','SLU'),
            ('Sao Luis - Marechal Cunha Machado International','Brazil','SLZ'),
            ('Santa Maria','Portugal','SMA'),
            ('Sacramento (CA)','USA','SMF'),
            ('Samos','Greece','SMI'),
            ('Santa Maria (CA)','USA','SMX'),
            ('Orange County (Santa Ana) (CA)','USA','SNA'),
            ('Salinas','Ecuador','SNC'),
            ('Shannon (Limerick)','Ireland','SNN'),
            ('Salinas (CA)','USA','SNS'),
            ('Sofia - Vrazhdebna','Bulgaria','SOF'),
            ('Sogndal','Norway','SOG'),
            ('South Molle Island','Australia','SOI'),
            ('Santo','Vanuatu','SON'),
            ('Sodankylae','Finland','SOT'),
            ('Southampton - Eastleigh','United Kingdom','SOU'),
            ('Santa Cruz de la Palma','Spain','SPC'),
            ('Springfield (IL)','USA','SPI'),
            ('Sapporo','Hokkaido Japan','SPK'),
            ('Saipan','Northern Mariana Islands','SPN'),
            ('Wichita Falls (TX)','USA','SPS'),
            ('Split','Croatia (Hrvatska)','SPU'),
            ('San Pedro','Cote d\'Ivoire','SPY'),
            ('Santa Rosa','Brazil','SRA'),
            ('Santa Rosa','Bolivia','SRB'),
            ('Santa Rosalia','Mexico','SRL'),
            ('Sarasota/Bradenton (FL)','USA','SRQ'),
            ('Santa Cruz de la Sierra','Bolivia','SRZ'),
            ('Salvador - Salvador International Airport','Brazil','SSA'),
            ('Malabo','Equatorial Guinea','SSG'),
            ('Sharm El Sheikh','Egypt','SSH'),
            ('Santa Rosalia','Colombia','SSL'),
            ('St. Louis (MO) Lambert–St. Louis International Airport','USA','STL'),
            ('London - Stansted','United Kingdom','STN'),
            ('Stockholm Metropolitan Area','Sweden','STO'),
            ('Stuttgart - Echterdingen','Germany','STR'),
            ('Santa Rosa (CA)','USA','STS'),
            ('St. Thomas','Virgin Islands (U.S.)','STT'),
            ('Surat','India','STV'),
            ('St. Croix','Virgin Islands (U.S.)','STX'),
            ('Surabaya - Juanda','Indonesia','SUB'),
            ('Lamezia Terme','Italy','SUF'),
            ('Sui','Pakistan','SUL'),
            ('Agana (Hagåtña)','Guam','SUM'),
            ('Sun Valley (ID)','USA','SUN'),
            ('Nausori','Fiji/Suva','SUV'),
            ('Sioux City IA','USA','SUX'),
            ('Kingstown - E. T. Joshua Airport','Saint Vincent and the Grenadines','SVD'),
            ('Stavanger','Norway','SVG'),
            ('Savonlinna','Finland','SVL'),
            ('Moscow - Sheremetyevo','Russia','SVO'),
            ('Sevilla','Spain','SVQ'),
            ('Newburgh (NY)','USA','SWF'),
            ('Swakopmund','Namibia','SWP'),
            ('Strassburg','France','SXB'),
            ('Berlin Schoenefeld','Germany','SXF'),
            ('Sligo','Ireland','SXL'),
            ('St. Marteen','Netherlands Antilles','SXM'),
            ('Srinagar','India','SXR'),
            ('Sydney','Australia','SYD'),
            ('Syracuse (NY)','USA','SYR'),
            ('Stornway','United Kingdom','SYY'),
            ('Kuala Lumpur - Sultan Abdul Aziz Shah','Malaysia','SZB'),
            ('Sheffield City Airport','United Kingdom','SZD'),
            ('Samsun','Turkey','SZF'),
            ('Salzburg - W.A. Mozart','Austria','SZG'),
            ('Skukuza','South Africa','SZK'),
            ('Shenzhen - Baoan','Guangdong PR China','SZX'),
            ('Stettin','Poland','SZZ'),
            ('Scarborough - Crown Point International','Trinidad and Tobago','TAB'),
            ('Takamatsu','Japan','TAK'),
            ('Tampico - Gen. F. Javier Mina','Mexico','TAM'),
            ('Qingdao','Shandong PR China','TAO'),
            ('Tashkent - International','Uzbekistan','TAS'),
            ('Taipei - Sung Shan','Taiwan','TAY'),
            ('Tbilisi - Novo Alexeyevka','Georgia','TBS'),
            ('Nuku\'alofa - Fua\'Amotu International','Tonga','TBU'),
            ('Tennant Creek','Australia','TCA'),
            ('Treasure Cay','Bahamas','TCB'),
            ('Tenerife','Spain','TCI'),
            ('Tuscaloosa (AL)','USA','TCL'),
            ('Thaba\'Nchu','South Africa','TCU'),
            ('Thisted','Denmark','TED'),
            ('Temora','Australia','TEM'),
            ('Tekirdag - Corlu','Turkey','TEQ'),
            ('Terceira','Portugal','TER'),
            ('Te Anau','New Zealand','TEU'),
            ('Telluride (CO)','USA','TEX'),
            ('Los Rodeos','Teneriffa/Spain','TFN'),
            ('Reina Sofia','Teneriffa/Spain','TFS'),
            ('Podgorica','Montenegro','TGD'),
            ('Tegucigalpa','Honduras','TGU'),
            ('Targovishte','Bulgaria','TGV'),
            ('Tuxtla Gutierrez','Mexico','TGZ'),
            ('Teresina','Brazil','THE'),
            ('Berlin Tempelhof (ceased operating in 2008)','Germany','THF'),
            ('Tehran (Teheran) - Mehrabad','Iran','THR'),
            ('Tirana - Rinas','Albania','TIA'),
            ('Taif','Saudi Arabia','TIF'),
            ('Tijuana - Rodriguez','Mexico','TIJ'),
            ('Tripoli - Tripoli International','Libya','TIP'),
            ('Thursday Island','Australia','TIS'),
            ('Tivat','Montenegro','TIV'),
            ('Talkeetna (AK)','USA','TKA'),
            ('Tokushima','Japan','TKS'),
            ('Turku','Finland','TKU'),
            ('Tallahassee (FL)','USA','TLH'),
            ('Tallinn - Ulemiste','Estonia','TLL'),
            ('Toulouse - Blagnac','France','TLS'),
            ('Tel Aviv - Ben Gurion International','Israel','TLV'),
            ('Tampere','Finland','TMP'),
            ('Sao Tome','Sao Tome & Principe','TMS'),
            ('Tamworth','Australia','TMW'),
            ('Termez (Termes)','Uzbekistan','TMZ'),
            ('Jinan','Shandong PR China','TNA'),
            ('Tangier - Boukhalef','Morocco','TNG'),
            ('Antananarivo (Tanannarive) - Ivato International Airport','Madagascar','TNR'),
            ('Tioman','Indonesia','TOD'),
            ('Toledo (OH)','USA','TOL'),
            ('Tromsoe','Norway','TOS'),
            ('Touho','New Caledonia','TOU'),
            ('Tortola','British Virgin Islands','TOV'),
            ('Toyama','Japan','TOY'),
            ('Tampa - International (FL)','USA','TPA'),
            ('Taipei - Chiang Kai Shek','Taiwan','TPE'),
            ('Tom Price','Australia','TPR'),
            ('Trapani','Italy','TPS'),
            ('Trondheim','Norway','TRD'),
            ('Oslo - Sandefjord','Norway','TRF'),
            ('Tri-Cities Regional (TN) /VA','USA','TRI'),
            ('Turin','Italy','TRN'),
            ('Taree','Australia','TRO'),
            ('Trieste','Italy','TRS'),
            ('Thiruvananthapuram','India','TRV'),
            ('Tiruchirapally','India','TRZ'),
            ('Tsumeb','Namibia','TSB'),
            ('Astana - Astana International Airport','Kazakhstan','TSE'),
            ('Treviso','Italy','TSF'),
            ('Tianjin','China','TSN'),
            ('Townsville','Australia','TSV'),
            ('Trenton/Princeton (NJ)','USA','TTN'),
            ('Turbat','Pakistan','TUK'),
            ('Tulsa (OK)','USA','TUL'),
            ('Tunis - Carthage','Tunisia','TUN'),
            ('Tulepo (MS)','USA','TUP'),
            ('Tucson (AZ)','USA','TUS'),
            ('Tabuk','Saudi Arabia','TUU'),
            ('Traverse City (MI)','USA','TVC'),
            ('Thief River Falls (MN)','USA','TVF'),
            ('Lake Tahoe (CA)','USA','TVL'),
            ('Toowoomba','Australia','TWB'),
            ('Twin Falls (ID)','USA','TWF'),
            ('Tawau','Malaysia','TWU'),
            ('Texarkana (AR)','USA','TXK'),
            ('Berlin Tegel','Germany','TXL'),
            ('Taiyuan','Shanxi PR China','TYN'),
            ('Tokyo','Japan','TYO'),
            ('Tyler (TX)','USA','TYR'),
            ('Knoxville (TN)','USA','TYS'),
            ('Trabzon','Turkey','TZX'),
            ('Ua Huka','French Polynesia','UAH'),
            ('Narsarsuaq','Greenland','UAK'),
            ('Ua Pou','French Polynesia','UAP'),
            ('Uberaba','Brazil','UBA'),
            ('Ube','Japan','UBJ'),
            ('Ubon Ratchathani - Muang Ubon Airport','Thailand','UBP'),
            ('Utica (NY) - Oneida County Airport','USA','UCA'),
            ('Ukhta','Russia','UCT'),
            ('Uden - Volkel Airport','Netherlands','UDE'),
            ('Uberlandia - Eduardo Gomes Airport','Brazil','UDI'),
            ('Uzhgorod','Ukraine','UDJ'),
            ('Udaipur - Dabok Airport','India','UDR'),
            ('Queenstown','Australia','UEE'),
            ('Quetta','Pakistan','UET'),
            ('Ufa','Russia','UFA'),
            ('Urgench','Uzbekistan','UGC'),
            ('Uige','Angola','UGO'),
            ('Uherske Hradiste','Czech Republic','UHE'),
            ('Utila','Honduras','UII'),
            ('Quincy (IL)','USA','UIN'),
            ('Quito - Mariscal Sucre International Airport','Ecuador','UIO'),
            ('Quimper','France','UIP'),
            ('Jaluit Island  ','Marshall Islands','UIT'),
            ('Kobe','Japan','UKB'),
            ('Ukiah (CA)','USA','UKI'),
            ('Kyoto','Japan','UKY'),
            ('Ulei','Vanuatu','ULB'),
            ('Ulundi','South Africa','ULD'),
            ('Ulaanbaatar - Buyant Uhaa Airport','Mongolia','ULN'),
            ('Gulu','Uganda','ULU'),
            ('Uummannaq','Greenland','UMD'),
            ('Umea','Sweden','UME'),
            ('Woomera','Australia','UMR'),
            ('Union Island','Saint Vincent and the Grenadines','UNI'),
            ('Unalakleet (AK)','USA','UNK'),
            ('Unst (Shetland Island) - Baltasound Airport','United Kingdom','UNT'),
            ('Ujung Pandang - Hasanudin Airport','Indonesia','UPG'),
            ('Upala','Costa Rica','UPL'),
            ('Uruapan','Mexico','UPN'),
            ('Upolu Point (HI)','USA','UPP'),
            ('Urubupunga - Ernesto Pochler Airport','Brazil','URB'),
            ('Urumqi','Xinjiang PR China','URC'),
            ('Uruguaiana - Ruben Berta Airport','Brazil','URG'),
            ('Uriman','Venezuela','URM'),
            ('Uruzgan','Afghanistan','URZ'),
            ('Ushuaia - Islas Malvinas Airport','Argentina','USH'),
            ('Ulsan','South Korea','USN'),
            ('Udon Thani','Thailand','UTH'),
            ('Upington','South Africa','UTN'),
            ('Utapao (Pattaya)','Thailand','UTP'),
            ('Umtata','South Africa','UTT'),
            ('Ulan-Ude','Russia','UUD'),
            ('Oyem','Gabon/Loyautte','UVE'),
            ('St. Lucia Hewanorra','Saint Lucia','UVF'),
            ('Kharga - New Valley','Egypt','UVL'),
            ('Vaasa','Finland','VAA'),
            ('Van - Ferit Melen','Turkey','VAN'),
            ('Valparaiso','Chile','VAP'),
            ('Varna','Bulgaria','VAR'),
            ('Sivas','Turkey','VAS'),
            ('Brescia Montichiari','Italy','VBS'),
            ('Visby','Sweden','VBY'),
            ('Venice - Marco Polo','Italy','VCE'),
            ('Sao Paulo - Viracopos','Brazil','VCP'),
            ('Elat Ovula','Israel','VDA'),
            ('Valverde','Spain','VDE'),
            ('Valdez (AK)','USA','VDZ'),
            ('Vernal (UT)','USA','VEL'),
            ('Veracruz','Mexico','VER'),
            ('Victoria Falls','Zimbabwe','VFA'),
            ('Vigo','Spain','VGO'),
            ('Vidin','Bulgaria','VID'),
            ('Wien (Vienna) - Vienna International','Austria','VIE'),
            ('Virgin Gorda','Virgin Islands (British)','VIJ'),
            ('Visalia (CA)','USA','VIS'),
            ('Vitoria','Spain','VIT'),
            ('Vitoria - Eurico de Aguiar Salles Airport','Brazil','VIX'),
            ('Moscow - Vnukovo','Russia','VKO'),
            ('Valencia','Spain','VLC'),
            ('Valdosta (GA)','USA','VLD'),
            ('Port Vila','Vanuatu','VLI'),
            ('Valladolid','Spain','VLL'),
            ('Valencia','Venezuela','VLN'),
            ('Velikiye Luki (Welikije Luki)','Russia','VLU'),
            ('Vilnius','Lithuania','VNO'),
            ('Varanasi','India','VNS'),
            ('Fort Walton Beach (FL)','USA','VPS'),
            ('Varadero','Cuba','VRA'),
            ('Vero Beach/Ft. Pierce (FL)','USA','VRB'),
            ('Varkaus','Finland','VRK'),
            ('Verona','Italy','VRN'),
            ('Villahermosa','Mexico','VSA'),
            ('Vasteras','Sweden','VST'),
            ('Vientiane - Wattay','Lao PDR','VTE'),
            ('Vaexjoe','Sweden','VXO'),
            ('Vryheid','South Africa','VYD'),
            ('Washington DC','USA','WAS'),
            ('Warsaw - Frédéric Chopin','Poland','WAW'),
            ('Windhoek - Hosea Kutako International','Namibia','WDH'),
            ('Weipa','Australia','WEI'),
            ('Welkom','South Africa','WEL'),
            ('Wagga','Australia','WGA'),
            ('Whakatane','New Zealand','WHK'),
            ('Wickham','Australia','WHM'),
            ('Wick','United Kingdom','WIC'),
            ('Wiesbaden Air Base','Germany','WIE'),
            ('Labouchere Bay (AK)','USA','WLB'),
            ('Wellington','New Zealand','WLG'),
            ('Wallis','Wallis and Futuna Islands','WLS'),
            ('Warrnambool','Australia','WMB'),
            ('Nawab Shah','Pakistan','WNS'),
            ('Wollongong','Australia','WOL'),
            ('Whangarei','New Zealand','WRE'),
            ('Wrangell (AK)','USA','WRG'),
            ('Worland (WY)','USA','WRL'),
            ('Wuhan','Hubei PR China','WUH'),
            ('Wiluna','Australia','WUN'),
            ('Walvis Bay','South Africa','WVB'),
            ('Whyalla','Australia','WYA'),
            ('Wyndham','Australia','WYN'),
            ('West Yellowstone (MT)','USA','WYS'),
            ('Xi\'an - Xianyang','Shaanxi PR China','XIY'),
            ('Lac Brochet MB','Canada','XLB'),
            ('Manihi','French Polynesia','XMH'),
            ('Xiamen','Fujian PR China','XMN'),
            ('Pukatawagan','Canada','XPK'),
            ('Jerez de la Frontera/Cadiz - La Parra','Spain','XRY'),
            ('South Indian Lake MB','Canada','XSI'),
            ('Singapore - Seletar','Singapore','XSP'),
            ('Yakutat (AK)','USA','YAK'),
            ('Yaounde','Cameroon','YAO'),
            ('Attawapiskat NT','Canada','YAT'),
            ('Uranium City','Canada','YBE'),
            ('Cambridge Bay','Canada','YCB'),
            ('Deer Lake/Corner Brook','Canada','YDF'),
            ('Edmonton','Canada','YEA'),
            ('Edmonton International','Canada','YEG'),
            ('Inuvik','Canada','YEV'),
            ('Fort Albert','Canada','YFA'),
            ('Iqaluit (Frobisher Bay)','Canada','YFB'),
            ('Fredericton','Canada','YFC'),
            ('Flin Flon','Canada','YFO'),
            ('La Grande','Canada','YGL'),
            ('Kuujjuarapik','Canada','YGW'),
            ('Gillam','Canada','YGX'),
            ('Hamilton','Canada','YHM'),
            ('Harrington Harbour PQ','Canada','YHR'),
            ('Halifax International','Canada','YHZ'),
            ('St. Augustin PQ','Canada','YIF'),
            ('Yichang','Hubei PR China','YIH'),
            ('Kamloops BC','Canada','YKA'),
            ('Yakima (WA)','USA','YKM'),
            ('Yakutsk','Russia','YKS'),
            ('Leaf Rapids','Canada','YLR'),
            ('Kelowna BC','Canada','YLW'),
            ('Fort McMurray','Canada','YMM'),
            ('Montreal','Canada','YMQ'),
            ('Montreal - Mirabel','Canada','YMX'),
            ('Yanbu','Saudi Arabia','YNB'),
            ('Yokohama','Japan','YOK'),
            ('Rainbow Lake AB','Canada','YOP'),
            ('Ottawa - Hull','Canada','YOW'),
            ('Port Menier PQ','Canada','YPN'),
            ('Prince Rupert/Digby Island','Canada','YPR'),
            ('Quebec - Quebec International','Canada','YQB'),
            ('The Pas','Canada','YQD'),
            ('Windsor Ontario','Canada','YQG'),
            ('Moncton','Canada','YQM'),
            ('Regina','Canada','YQR'),
            ('Thunder Bay','Canada','YQT'),
            ('Gander','Canada','YQX'),
            ('Resolute Bay','Canada','YRB'),
            ('Saint John','Canada','YSJ'),
            ('Fort Smith','Canada','YSM'),
            ('Nanisivik','Canada','YSR'),
            ('Thompson','Canada','YTH'),
            ('Toronto','Canada','YTO'),
            ('Toronto - Billy Bishop Toronto City Airport','Canada','YTZ'),
            ('Umiujaq','Canada','YUD'),
            ('Montreal - Dorval (Montréal-Trudeau)','Canada','YUL'),
            ('Yuma (AZ)','USA','YUM'),
            ('Hall Beach','Canada','YUX'),
            ('Moroni - Iconi','Comoros (Comores)','YVA'),
            ('Bonaventure PQ','Canada','YVB'),
            ('Val d\'Or','Canada','YVO'),
            ('Kuujjuaq (FortChimo)','Canada','YVP'),
            ('Norman Wells','Canada','YVQ'),
            ('Vancouver - Vancouver International','Canada','YVR'),
            ('Winnipeg International','Canada','YWG'),
            ('Wabush','Canada','YWK'),
            ('Edmonton Municipal','Canada','YXD'),
            ('Saskatoon','Canada','YXE'),
            ('Fort St. John','Canada','YXJ'),
            ('Whale Cove NT','Canada','YXN'),
            ('Prince George','Canada','YXS'),
            ('Terrace','Canada','YXT'),
            ('London','Canada','YXU'),
            ('Whitehorse','Canada','YXY'),
            ('Calgary - Calgary International Airport','Canada','YYC'),
            ('Smithers','Canada','YYD'),
            ('Victoria','Canada','YYJ'),
            ('Churchill','Canada','YYQ'),
            ('Goose Bay','Canada','YYR'),
            ('St. John\'s','Canada','YYT'),
            ('Toronto - Toronto Pearson International Airport','Canada','YYZ'),
            ('Yellowknife','Canada','YZF'),
            ('Sandspit','Canada','YZP'),
            ('Zadar','Croatia (Hrvatska)','ZAD'),
            ('Zagreb - Pleso','Croatia (Hrvatska)','ZAG'),
            ('Zaragoza','Spain','ZAZ'),
            ('Bowen','Australia','ZBO'),
            ('Zacatecas','Mexico','ZCL'),
            ('Berne Railway Service','Switzerland','ZDJ'),
            ('Ixtapa/Zihuatenejo','Mexico','ZIH'),
            ('Hong Kong - Chek Lap Kok','Hong Kong','ZJK'),
            ('Kaschechawan PQ','Canada','ZKE'),
            ('Manzanillo','Mexico','ZLO'),
            ('Zinder','Niger','ZND'),
            ('Newman','Australia','ZNE'),
            ('Queenstown','New Zealand','ZQN'),
            ('Zurich (Zürich) - Kloten','Switzerland','ZRH'),
            ('San Salvador','Bahamas','ZSA'),
            ('Sassandra','Cote d\'Ivoire','ZSS'),
            ('Zakynthos','Greece','ZTH'),
            ('Shamattawa MB','Canada','ZTM'),
            ('Sylhet','Bangladesh','ZYL');
        ");
    }

    public function down()
    {
        $this->execute('DROP table airports');
    }
}
