#!/usr/bin/env sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ "$CFP_ENV" = "" ]; then
    export CFP_ENV="development"
fi

echo "==> Setting up DB..."
php vendor/bin/phinx migrate -e $CFP_ENV

echo "==> App is now ready to go!"
