#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

if [ "x$CFP_ENV" = "x" ]; then
    export CFP_ENV="development"
fi

echo "==> Installing dependencies..."
if command -v composer &>/dev/null; then
    composer install
elif [ -f "composer.phar" ]; then
    php composer.phar install
else
    echo "ERROR: Composer path unknown. Please install composer or download composer.phar"
    exit 1
fi

if [ ! -f "config/$CFP_ENV.yml" ]; then
    echo "Missing config/$CFP_ENV.yml, be sure to copy from config/$CFP_ENV.yml.dist and update config"
    exit 1
fi
