#!/bin/sh

# script/docker: Set things up so the app will run in the Docker container

set -e

cd "$(dirname "$0")/.."

echo "==> Installing dependencies..."
if command -v composer &>/dev/null; then
    composer install
elif [ -f "composer.phar" ]; then
    php composer.phar install
else
    echo "ERROR: Composer path unknown. Please install composer or download composer.phar"
    exit 1
fi

echo "==> Clearing caches..."
bin/console --env=$CFP_ENV cache:clear

echo "==> Running migrations..."
bin/console doctrine:migrations:migrate --env=$CFP_ENV
