#!/bin/bash

# script/server: Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

export PHPVER=$(php -r "echo PHP_VERSION;")
if [ "$PHPVER" = "7.1.12" ]; then
    CFP_ENV=development php -S localhost:8000 -t web ../server.php
else
    CFP_ENV=development php -S localhost:8000 -t web server.php
fi
