#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ "x$CFP_ENV" = "x" ]; then
    export CFP_ENV="development"
fi

echo "==> Setting up DB..."
vendor/bin/phinx migrate -e $CFP_ENV

echo "==> App is now ready to go!"
