#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ ! -f "phinx.yml" ]; then
    echo "Missing phinx.yml, be sure to copy from phinx.yml.dist and update config"
    exit 1
fi

if [ ! -f "config/development.yml" ]; then
    echo "Missing config/development.yml, be sure to copy from config/development.dist.yml and update config"
    exit 1
fi

echo "==> Setting up DB..."
vendor/bin/phinx migrate

echo "==> App is now ready to go!"
