#!/usr/bin/env sh
set -e

echo "Build hook running"

TAG=$1

export COMMIT_HASH=`git rev-parse --short HEAD`

export IMAGE_COMMIT=opencfp/opencfp:$TAG-$COMMIT_HASH

export IMAGE_NAME=opencfp/opencfp:$TAG && \
             docker build --no-cache --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file ./.docker/Dockerfile \
             --build-arg VCS_REF=$COMMIT_HASH \
             --build-arg DOCKER_REPO=$DOCKER_REPO \
             --build-arg IMAGE_NAME=$IMAGE_NAME \
             --squash --force-rm --compress --rm \
             -t $IMAGE_NAME .
